/*
###############################################################
#  Generated by:      Cadence Innovus 17.13-s098_1
#  OS:                Linux x86_64(Host ID fasic-beast1.fnal.gov)
#  Generated on:      Fri Aug  9 17:01:03 2019
#  Design:            SRO_CTRL
#  Command:           saveNetlist ../output/export.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.13-s036_1
// Generated on: Aug  9 2019 15:27:31 CDT (Aug  9 2019 20:27:31 UTC)
// Verification Directory fv/SRO_CTRL 
`timescale 1ps/100fs
module SRO_CTRL (
	clock, 
	reset, 
	l1acc, 
	bc0, 
	roi, 
	we, 
	addr, 
	roe, 
	din0, 
	din1, 
	din2, 
	din3, 
	dout, 
	VDD, 
	VSS);
   input clock;
   input reset;
   input l1acc;
   input bc0;
   input [15:0] roi;
   output we;
   output [7:0] addr;
   output [3:0] roe;
   input [29:0] din0;
   input [29:0] din1;
   input [29:0] din2;
   input [29:0] din3;
   output [29:0] dout;
   inout VDD;
   inout VSS;

   // Internal wires
   wire FE_PDN142_n_152;
   wire FE_PDN141_addr_5;
   wire FE_PDN139_addr_1;
   wire FE_PHN138_n_236;
   wire FE_PHN137_n_245;
   wire FE_PHN136_n_233;
   wire FE_PHN135_n_246;
   wire FE_PHN134_n_235;
   wire FE_PHN133_n_239;
   wire FE_PHN132_n_227;
   wire FE_PHN131_n_238;
   wire FE_PHN130_n_230;
   wire FE_PHN129_n_234;
   wire FE_PHN128_n_229;
   wire FE_PHN127_n_232;
   wire FE_PHN126_n_249;
   wire FE_PHN125_n_409;
   wire FE_PHN124_n_411;
   wire FE_PHN123_n_250;
   wire FE_PHN122_n_243;
   wire FE_PHN121_n_241;
   wire FE_PHN120_n_49;
   wire FE_PHN119_n_48;
   wire FE_PHN118_n_3;
   wire FE_PHN117_n_2;
   wire FE_PHN116_n_1;
   wire FE_PHN115_bcid_reg_10;
   wire FE_PHN114_bcid_reg_6;
   wire FE_PHN113_bcid_reg_7;
   wire FE_PHN112_bcid_reg_5;
   wire FE_PHN111_n_80;
   wire FE_PHN110_n_0;
   wire FE_PHN109_bcid_reg_4;
   wire FE_PHN108_bcid_reg_3;
   wire FE_PHN107_bcid_reg_11;
   wire FE_PHN106_bcid_reg_9;
   wire FE_PHN105_bcid_reg_0;
   wire FE_PHN104_bcid_reg_2;
   wire FE_PHN103_bcid_reg_8;
   wire FE_PHN102_bcid_reg_1;
   wire FE_PHN101_n_407;
   wire FE_PHN100_state_1;
   wire FE_PHN99_state_0;
   wire FE_PHN98_roi_reg_11;
   wire FE_PHN97_roi_reg_14;
   wire FE_PHN96_addr_3;
   wire FE_PHN95_addr_1;
   wire FE_PHN94_addr_7;
   wire FE_PHN93_state_2;
   wire FE_PHN92_FE_OFN0_addr_0;
   wire FE_PHN91_addr_5;
   wire FE_PHN90_addr_2;
   wire FE_PHN89_addr_4;
   wire FE_PHN88_addr_6;
   wire FE_PDN87_n_196;
   wire FE_PDN86_n_137;
   wire FE_PDN84_dout_10;
   wire FE_PDN82_dout_24;
   wire FE_PDN81_n_220;
   wire FE_PDN79_dout_29;
   wire FE_PDN78_n_74;
   wire FE_PDN77_n_212;
   wire FE_PDN76_n_29;
   wire FE_PDN75_n_35;
   wire FE_PDN74_n_243;
   wire FE_PDN73_FE_OFN2_n_242;
   wire FE_PDN72_roi_reg_14;
   wire FE_PDN71_n_196;
   wire FE_PDN70_n_66;
   wire FE_PDN69_roi_reg_11;
   wire FE_PDN67_addr_5;
   wire FE_PDN65_addr_3;
   wire FE_PDN63_addr_4;
   wire FE_PHN62_addr_3;
   wire FE_PHN61_roi_reg_14;
   wire FE_PHN60_roi_reg_14;
   wire FE_PHN59_roi_reg_13;
   wire FE_PHN58_roi_reg_12;
   wire FE_PHN57_roi_reg_10;
   wire FE_PHN56_roi_reg_7;
   wire FE_PHN55_roi_reg_11;
   wire FE_PHN54_roi_reg_3;
   wire FE_PHN53_roi_reg_6;
   wire FE_PHN52_roi_reg_8;
   wire FE_PHN51_roi_reg_9;
   wire FE_PHN50_roi_reg_5;
   wire FE_PHN49_roi_reg_4;
   wire FE_PHN48_roi_reg_2;
   wire FE_PHN47_roi_reg_1;
   wire FE_PHN46_roi_reg_0;
   wire FE_PHN44_addr_3;
   wire FE_PHN43_addr_2;
   wire FE_PHN42_addr_6;
   wire FE_PHN41_addr_1;
   wire FE_PHN39_addr_5;
   wire FE_PHN37_addr_4;
   wire FE_PHN35_addr_7;
   wire FE_PHN34_n_48;
   wire FE_PHN33_n_49;
   wire FE_PHN32_state_0;
   wire FE_PHN31_state_1;
   wire FE_PHN30_n_407;
   wire FE_PHN29_bcid_reg_1;
   wire FE_PHN28_bcid_reg_0;
   wire FE_PHN27_bcid_reg_5;
   wire FE_PHN26_bcid_reg_3;
   wire FE_PHN25_n_80;
   wire FE_PHN24_bcid_reg_2;
   wire FE_PHN23_n_3;
   wire FE_PHN22_n_2;
   wire FE_PHN21_n_1;
   wire FE_PHN20_bcid_reg_4;
   wire FE_PHN19_bcid_reg_9;
   wire FE_PHN18_bcid_reg_10;
   wire FE_PHN17_bcid_reg_6;
   wire FE_PHN16_bcid_reg_7;
   wire FE_PHN15_bcid_reg_8;
   wire FE_PHN14_n_0;
   wire FE_PHN13_bcid_reg_11;
   wire FE_OFN12_dout_26;
   wire FE_OFN11_roe_0;
   wire FE_OFN10_roe_3;
   wire CTS_2;
   wire FE_OFN9_dout_4;
   wire FE_OFN8_dout_8;
   wire FE_OFN7_dout_12;
   wire FE_OFN6_dout_13;
   wire FE_OFN5_dout_14;
   wire FE_OFN4_dout_15;
   wire FE_OFN3_dout_16;
   wire FE_OFN2_n_242;
   wire FE_OFN1_dout_20;
   wire FE_OFN0_addr_0;
   wire [2:0] state;
   wire [15:0] roi_reg;
   wire [11:0] l1acc_id_reg;
   wire [11:0] bcid_reg;
   wire [7:0] stop_reg;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_87;
   wire n_88;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_212;
   wire n_214;
   wire n_217;
   wire n_219;
   wire n_220;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_259;
   wire n_407;
   wire n_409;
   wire n_410;
   wire n_411;

   CKBD1 FE_PDC142_n_152 (.I(n_152),
	.Z(FE_PDN142_n_152));
   CKBD1 FE_PDC141_addr_5 (.I(FE_PDN67_addr_5),
	.Z(FE_PDN141_addr_5));
   CKBD1 FE_PDC140_addr_1 (.I(FE_PDN139_addr_1),
	.Z(addr[1]));
   DEL015 FE_PHC138_n_236 (.I(FE_PHN138_n_236),
	.Z(n_236));
   DEL1 FE_PHC137_n_245 (.I(n_245),
	.Z(FE_PHN137_n_245));
   DEL0 FE_PHC136_n_233 (.I(n_233),
	.Z(FE_PHN136_n_233));
   DEL0 FE_PHC135_n_246 (.I(n_246),
	.Z(FE_PHN135_n_246));
   DEL0 FE_PHC134_n_235 (.I(n_235),
	.Z(FE_PHN134_n_235));
   DEL0 FE_PHC133_n_239 (.I(FE_PHN133_n_239),
	.Z(n_239));
   DEL0 FE_PHC132_n_227 (.I(n_227),
	.Z(FE_PHN132_n_227));
   DEL0 FE_PHC131_n_238 (.I(FE_PHN131_n_238),
	.Z(n_238));
   DEL0 FE_PHC130_n_230 (.I(FE_PHN130_n_230),
	.Z(n_230));
   DEL0 FE_PHC129_n_234 (.I(n_234),
	.Z(FE_PHN129_n_234));
   DEL0 FE_PHC128_n_229 (.I(n_229),
	.Z(FE_PHN128_n_229));
   DEL0 FE_PHC127_n_232 (.I(n_232),
	.Z(FE_PHN127_n_232));
   DEL0 FE_PHC126_n_249 (.I(FE_PHN126_n_249),
	.Z(n_249));
   DEL0 FE_PHC125_n_409 (.I(FE_PHN125_n_409),
	.Z(n_409));
   DEL0 FE_PHC124_n_411 (.I(n_411),
	.Z(FE_PHN124_n_411));
   DEL0 FE_PHC123_n_250 (.I(n_250),
	.Z(FE_PHN123_n_250));
   DEL0 FE_PHC122_n_243 (.I(FE_PHN122_n_243),
	.Z(n_243));
   DEL0 FE_PHC121_n_241 (.I(n_241),
	.Z(FE_PHN121_n_241));
   DEL01 FE_PHC120_n_49 (.I(FE_PHN33_n_49),
	.Z(FE_PHN120_n_49));
   DEL01 FE_PHC119_n_48 (.I(n_48),
	.Z(FE_PHN119_n_48));
   DEL015 FE_PHC118_n_3 (.I(FE_PHN118_n_3),
	.Z(FE_PHN23_n_3));
   DEL015 FE_PHC117_n_2 (.I(FE_PHN22_n_2),
	.Z(FE_PHN117_n_2));
   DEL015 FE_PHC116_n_1 (.I(FE_PHN21_n_1),
	.Z(FE_PHN116_n_1));
   DEL015 FE_PHC115_bcid_reg_10 (.I(bcid_reg[10]),
	.Z(FE_PHN115_bcid_reg_10));
   DEL015 FE_PHC114_bcid_reg_6 (.I(FE_PHN17_bcid_reg_6),
	.Z(FE_PHN114_bcid_reg_6));
   DEL015 FE_PHC113_bcid_reg_7 (.I(FE_PHN16_bcid_reg_7),
	.Z(FE_PHN113_bcid_reg_7));
   DEL015 FE_PHC112_bcid_reg_5 (.I(FE_PHN27_bcid_reg_5),
	.Z(FE_PHN112_bcid_reg_5));
   DEL01 FE_PHC111_n_80 (.I(FE_PHN111_n_80),
	.Z(FE_PHN25_n_80));
   DEL0 FE_PHC110_n_0 (.I(FE_PHN14_n_0),
	.Z(FE_PHN110_n_0));
   DEL015 FE_PHC109_bcid_reg_4 (.I(FE_PHN109_bcid_reg_4),
	.Z(FE_PHN20_bcid_reg_4));
   DEL015 FE_PHC108_bcid_reg_3 (.I(FE_PHN108_bcid_reg_3),
	.Z(FE_PHN26_bcid_reg_3));
   DEL015 FE_PHC107_bcid_reg_11 (.I(FE_PHN107_bcid_reg_11),
	.Z(FE_PHN13_bcid_reg_11));
   DEL015 FE_PHC106_bcid_reg_9 (.I(FE_PHN19_bcid_reg_9),
	.Z(FE_PHN106_bcid_reg_9));
   DEL015 FE_PHC105_bcid_reg_0 (.I(FE_PHN28_bcid_reg_0),
	.Z(FE_PHN105_bcid_reg_0));
   DEL015 FE_PHC104_bcid_reg_2 (.I(FE_PHN24_bcid_reg_2),
	.Z(FE_PHN104_bcid_reg_2));
   DEL015 FE_PHC103_bcid_reg_8 (.I(FE_PHN15_bcid_reg_8),
	.Z(FE_PHN103_bcid_reg_8));
   DEL015 FE_PHC102_bcid_reg_1 (.I(FE_PHN29_bcid_reg_1),
	.Z(FE_PHN102_bcid_reg_1));
   DEL0 FE_PHC101_n_407 (.I(FE_PHN101_n_407),
	.Z(n_407));
   DEL0 FE_PHC100_state_1 (.I(FE_PHN100_state_1),
	.Z(state[1]));
   DEL0 FE_PHC99_state_0 (.I(state[0]),
	.Z(FE_PHN99_state_0));
   DEL1 FE_PHC98_roi_reg_11 (.I(FE_PHN55_roi_reg_11),
	.Z(FE_PHN98_roi_reg_11));
   DEL0 FE_PHC97_roi_reg_14 (.I(FE_PHN60_roi_reg_14),
	.Z(FE_PHN97_roi_reg_14));
   DEL1 FE_PHC96_addr_3 (.I(FE_PHN44_addr_3),
	.Z(FE_PHN96_addr_3));
   DEL1 FE_PHC95_addr_1 (.I(FE_PHN41_addr_1),
	.Z(FE_PHN95_addr_1));
   DEL1 FE_PHC94_addr_7 (.I(FE_PHN94_addr_7),
	.Z(FE_PHN35_addr_7));
   DEL0 FE_PHC93_state_2 (.I(state[2]),
	.Z(FE_PHN93_state_2));
   DEL1 FE_PHC92_FE_OFN0_addr_0 (.I(FE_PHN92_FE_OFN0_addr_0),
	.Z(FE_OFN0_addr_0));
   DEL1 FE_PHC91_addr_5 (.I(FE_PHN39_addr_5),
	.Z(FE_PHN91_addr_5));
   DEL1 FE_PHC90_addr_2 (.I(FE_PHN43_addr_2),
	.Z(FE_PHN90_addr_2));
   DEL1 FE_PHC89_addr_4 (.I(FE_PHN37_addr_4),
	.Z(FE_PHN89_addr_4));
   DEL1 FE_PHC88_addr_6 (.I(FE_PHN42_addr_6),
	.Z(FE_PHN88_addr_6));
   CKBD1 FE_PDC87_n_196 (.I(n_196),
	.Z(FE_PDN87_n_196));
   CKBD1 FE_PDC86_n_137 (.I(n_137),
	.Z(FE_PDN86_n_137));
   CKBD1 FE_PDC85_dout_10 (.I(FE_PDN84_dout_10),
	.Z(dout[10]));
   CKBD1 FE_PDC83_dout_24 (.I(FE_PDN82_dout_24),
	.Z(dout[24]));
   CKBD1 FE_PDC81_n_220 (.I(n_220),
	.Z(FE_PDN81_n_220));
   CKBD1 FE_PDC80_dout_29 (.I(FE_PDN79_dout_29),
	.Z(dout[29]));
   CKBD1 FE_PDC78_n_74 (.I(n_74),
	.Z(FE_PDN78_n_74));
   CKBD1 FE_PDC77_n_212 (.I(n_212),
	.Z(FE_PDN77_n_212));
   CKBD1 FE_PDC76_n_29 (.I(n_29),
	.Z(FE_PDN76_n_29));
   CKBD1 FE_PDC75_n_35 (.I(n_35),
	.Z(FE_PDN75_n_35));
   BUFFD2 FE_PDC74_n_243 (.I(n_243),
	.Z(FE_PDN74_n_243));
   BUFFD2 FE_PDC73_FE_OFN2_n_242 (.I(FE_OFN2_n_242),
	.Z(FE_PDN73_FE_OFN2_n_242));
   CKBD1 FE_PDC72_roi_reg_14 (.I(roi_reg[14]),
	.Z(FE_PDN72_roi_reg_14));
   CKBD1 FE_PDC71_n_196 (.I(n_196),
	.Z(FE_PDN71_n_196));
   CKBD1 FE_PDC70_n_66 (.I(n_66),
	.Z(FE_PDN70_n_66));
   CKBD1 FE_PDC69_roi_reg_11 (.I(roi_reg[11]),
	.Z(FE_PDN69_roi_reg_11));
   CKBD1 FE_PDC68_addr_5 (.I(FE_PDN141_addr_5),
	.Z(addr[5]));
   CKBD1 FE_PDC66_addr_3 (.I(FE_PDN65_addr_3),
	.Z(addr[3]));
   CKBD1 FE_PDC64_addr_4 (.I(FE_PDN63_addr_4),
	.Z(addr[4]));
   CKBD1 FE_PHC62_addr_3 (.I(FE_PDN65_addr_3),
	.Z(FE_PHN62_addr_3));
   BUFFD1 FE_PHC61_roi_reg_14 (.I(FE_PDN72_roi_reg_14),
	.Z(FE_PHN61_roi_reg_14));
   CKBD0 FE_PHC60_roi_reg_14 (.I(FE_PHN97_roi_reg_14),
	.Z(roi_reg[14]));
   DEL0 FE_PHC59_roi_reg_13 (.I(FE_PHN59_roi_reg_13),
	.Z(roi_reg[13]));
   DEL0 FE_PHC58_roi_reg_12 (.I(roi_reg[12]),
	.Z(FE_PHN58_roi_reg_12));
   DEL0 FE_PHC57_roi_reg_10 (.I(FE_PHN57_roi_reg_10),
	.Z(roi_reg[10]));
   DEL0 FE_PHC56_roi_reg_7 (.I(FE_PHN56_roi_reg_7),
	.Z(roi_reg[7]));
   CKBD0 FE_PHC55_roi_reg_11 (.I(FE_PHN98_roi_reg_11),
	.Z(roi_reg[11]));
   DEL3 FE_PHC54_roi_reg_3 (.I(FE_PHN54_roi_reg_3),
	.Z(roi_reg[3]));
   DEL0 FE_PHC53_roi_reg_6 (.I(FE_PHN53_roi_reg_6),
	.Z(roi_reg[6]));
   DEL0 FE_PHC52_roi_reg_8 (.I(FE_PHN52_roi_reg_8),
	.Z(roi_reg[8]));
   DEL0 FE_PHC51_roi_reg_9 (.I(roi_reg[9]),
	.Z(FE_PHN51_roi_reg_9));
   DEL0 FE_PHC50_roi_reg_5 (.I(roi_reg[5]),
	.Z(FE_PHN50_roi_reg_5));
   DEL0 FE_PHC49_roi_reg_4 (.I(FE_PHN49_roi_reg_4),
	.Z(roi_reg[4]));
   DEL0 FE_PHC48_roi_reg_2 (.I(FE_PHN48_roi_reg_2),
	.Z(roi_reg[2]));
   DEL0 FE_PHC47_roi_reg_1 (.I(FE_PHN47_roi_reg_1),
	.Z(roi_reg[1]));
   DEL0 FE_PHC46_roi_reg_0 (.I(FE_PHN46_roi_reg_0),
	.Z(roi_reg[0]));
   BUFFD0 FE_PHC45_addr_3 (.I(FE_PHN96_addr_3),
	.Z(FE_PDN65_addr_3));
   CKBD2 FE_PHC43_addr_2 (.I(FE_PHN90_addr_2),
	.Z(addr[2]));
   CKBD2 FE_PHC42_addr_6 (.I(FE_PHN88_addr_6),
	.Z(addr[6]));
   BUFFD1 FE_PHC41_addr_1 (.I(FE_PHN95_addr_1),
	.Z(FE_PDN139_addr_1));
   BUFFD0 FE_PHC40_addr_5 (.I(FE_PHN91_addr_5),
	.Z(FE_PDN67_addr_5));
   BUFFD0 FE_PHC38_addr_4 (.I(FE_PHN89_addr_4),
	.Z(FE_PDN63_addr_4));
   CKBD1 FE_PHC36_addr_7 (.I(FE_PHN35_addr_7),
	.Z(addr[7]));
   DEL0 FE_PHC34_n_48 (.I(FE_PHN34_n_48),
	.Z(n_48));
   DEL0 FE_PHC33_n_49 (.I(FE_PHN120_n_49),
	.Z(n_49));
   BUFFD1 FE_PHC32_state_0 (.I(FE_PHN99_state_0),
	.Z(FE_PHN32_state_0));
   DEL0 FE_PHC31_state_1 (.I(state[1]),
	.Z(FE_PHN31_state_1));
   DEL0 FE_PHC30_n_407 (.I(n_407),
	.Z(FE_PHN30_n_407));
   DEL0 FE_PHC29_bcid_reg_1 (.I(FE_PHN102_bcid_reg_1),
	.Z(bcid_reg[1]));
   DEL0 FE_PHC28_bcid_reg_0 (.I(FE_PHN105_bcid_reg_0),
	.Z(bcid_reg[0]));
   DEL0 FE_PHC27_bcid_reg_5 (.I(FE_PHN112_bcid_reg_5),
	.Z(bcid_reg[5]));
   DEL0 FE_PHC26_bcid_reg_3 (.I(FE_PHN26_bcid_reg_3),
	.Z(bcid_reg[3]));
   DEL0 FE_PHC25_n_80 (.I(FE_PHN25_n_80),
	.Z(n_80));
   DEL0 FE_PHC24_bcid_reg_2 (.I(FE_PHN104_bcid_reg_2),
	.Z(bcid_reg[2]));
   DEL0 FE_PHC23_n_3 (.I(FE_PHN23_n_3),
	.Z(n_3));
   DEL0 FE_PHC22_n_2 (.I(FE_PHN117_n_2),
	.Z(n_2));
   DEL0 FE_PHC21_n_1 (.I(FE_PHN116_n_1),
	.Z(n_1));
   DEL0 FE_PHC20_bcid_reg_4 (.I(FE_PHN20_bcid_reg_4),
	.Z(bcid_reg[4]));
   DEL0 FE_PHC19_bcid_reg_9 (.I(FE_PHN106_bcid_reg_9),
	.Z(bcid_reg[9]));
   DEL0 FE_PHC18_bcid_reg_10 (.I(FE_PHN115_bcid_reg_10),
	.Z(FE_PHN18_bcid_reg_10));
   DEL0 FE_PHC17_bcid_reg_6 (.I(FE_PHN114_bcid_reg_6),
	.Z(bcid_reg[6]));
   DEL0 FE_PHC16_bcid_reg_7 (.I(FE_PHN113_bcid_reg_7),
	.Z(bcid_reg[7]));
   DEL0 FE_PHC15_bcid_reg_8 (.I(FE_PHN103_bcid_reg_8),
	.Z(bcid_reg[8]));
   DEL0 FE_PHC14_n_0 (.I(FE_PHN110_n_0),
	.Z(n_0));
   DEL0 FE_PHC13_bcid_reg_11 (.I(FE_PHN13_bcid_reg_11),
	.Z(bcid_reg[11]));
   CKBD3 FE_OFC12_dout_26 (.I(FE_OFN12_dout_26),
	.Z(dout[26]));
   CKBD3 FE_OFC11_roe_0 (.I(FE_OFN11_roe_0),
	.Z(roe[0]));
   CKBD3 FE_OFC10_roe_3 (.I(FE_OFN10_roe_3),
	.Z(roe[3]));
   CKBD16 CTS_ccl_a_BUF_clk_0_G0_L1_1 (.I(clock),
	.Z(CTS_2));
   CKBD1 FE_OFC9_dout_4 (.I(FE_OFN9_dout_4),
	.Z(dout[4]));
   CKBD1 FE_OFC8_dout_8 (.I(FE_OFN8_dout_8),
	.Z(dout[8]));
   CKBD1 FE_OFC7_dout_12 (.I(FE_OFN7_dout_12),
	.Z(dout[12]));
   CKBD1 FE_OFC6_dout_13 (.I(FE_OFN6_dout_13),
	.Z(dout[13]));
   CKBD1 FE_OFC5_dout_14 (.I(FE_OFN5_dout_14),
	.Z(dout[14]));
   CKBD1 FE_OFC4_dout_15 (.I(FE_OFN4_dout_15),
	.Z(dout[15]));
   CKBD1 FE_OFC3_dout_16 (.I(FE_OFN3_dout_16),
	.Z(dout[16]));
   BUFFD3 FE_OFC2_n_242 (.I(n_242),
	.Z(FE_OFN2_n_242));
   CKBD1 FE_OFC1_dout_20 (.I(FE_OFN1_dout_20),
	.Z(dout[20]));
   BUFFD1 FE_OFC0_addr_0 (.I(FE_OFN0_addr_0),
	.Z(addr[0]));
   DFQD1 \addr_reg_reg[7]  (.CP(CTS_2),
	.D(n_251),
	.Q(FE_PHN94_addr_7));
   DFQD1 \addr_reg_reg[6]  (.CP(CTS_2),
	.D(n_253),
	.Q(FE_PHN42_addr_6));
   DFQD1 \addr_reg_reg[5]  (.CP(CTS_2),
	.D(n_252),
	.Q(FE_PHN39_addr_5));
   DFQD1 \addr_reg_reg[1]  (.CP(CTS_2),
	.D(n_254),
	.Q(FE_PHN41_addr_1));
   DFQD1 \addr_reg_reg[3]  (.CP(CTS_2),
	.D(n_255),
	.Q(FE_PHN44_addr_3));
   DFQD1 \addr_reg_reg[4]  (.CP(CTS_2),
	.D(n_256),
	.Q(FE_PHN37_addr_4));
   DFQD1 \addr_reg_reg[2]  (.CP(CTS_2),
	.D(n_259),
	.Q(FE_PHN43_addr_2));
   SDFQD0 \addr_reg_reg[0]  (.CP(CTS_2),
	.D(n_409),
	.Q(FE_PHN92_FE_OFN0_addr_0),
	.SE(addr[0]),
	.SI(n_257));
   AO22D0 p20222A7837 (.A1(n_409),
	.A2(n_47),
	.B1(addr[2]),
	.B2(n_257),
	.Z(n_259));
   AO22D0 p20222A36747557 (.A1(n_409),
	.A2(n_77),
	.B1(FE_PDN63_addr_4),
	.B2(n_257),
	.Z(n_256));
   AO22D0 p20222A36757654 (.A1(n_409),
	.A2(n_71),
	.B1(FE_PDN65_addr_3),
	.B2(n_257),
	.Z(n_255));
   AO22D0 p20222A36768867 (.A1(n_409),
	.A2(n_19),
	.B1(addr[1]),
	.B2(n_257),
	.Z(n_254));
   AO22D0 p20222A36771377 (.A1(n_409),
	.A2(n_72),
	.B1(addr[6]),
	.B2(n_257),
	.Z(n_253));
   AO22D0 p20222A36783717 (.A1(n_409),
	.A2(n_101),
	.B1(FE_PDN67_addr_5),
	.B2(n_257),
	.Z(n_252));
   AO22D0 p20222A36794599 (.A1(n_409),
	.A2(n_87),
	.B1(addr[7]),
	.B2(n_257),
	.Z(n_251));
   AO221D0 p21126A3779 (.A1(n_224),
	.A2(n_151),
	.B1(n_248),
	.B2(FE_PHN32_state_0),
	.C(n_247),
	.Z(n_250));
   DFQD1 \roi_reg_reg[0]  (.CP(CTS_2),
	.D(FE_PHN137_n_245),
	.Q(FE_PHN46_roi_reg_0));
   DFQD1 \roi_reg_reg[4]  (.CP(CTS_2),
	.D(n_236),
	.Q(FE_PHN49_roi_reg_4));
   DFQD1 \roi_reg_reg[8]  (.CP(CTS_2),
	.D(FE_PHN127_n_232),
	.Q(FE_PHN52_roi_reg_8));
   DFQD1 \roi_reg_reg[1]  (.CP(CTS_2),
	.D(n_239),
	.Q(FE_PHN47_roi_reg_1));
   DFQD1 \roi_reg_reg[12]  (.CP(CTS_2),
	.D(n_230),
	.Q(roi_reg[12]));
   DFQD1 \roi_reg_reg[13]  (.CP(CTS_2),
	.D(FE_PHN128_n_229),
	.Q(FE_PHN59_roi_reg_13));
   DFQD1 \roi_reg_reg[15]  (.CP(CTS_2),
	.D(n_226),
	.Q(FE_PHN101_n_407));
   ND2D1 p20300A2007 (.A1(reset),
	.A2(FE_PHN121_n_241),
	.ZN(n_257));
   DFQD1 \roi_reg_reg[9]  (.CP(CTS_2),
	.D(FE_PHN129_n_234),
	.Q(roi_reg[9]));
   DFQD1 \roi_reg_reg[5]  (.CP(CTS_2),
	.D(FE_PHN134_n_235),
	.Q(roi_reg[5]));
   DFQD1 \roi_reg_reg[2]  (.CP(CTS_2),
	.D(n_238),
	.Q(FE_PHN48_roi_reg_2));
   DFQD1 \roi_reg_reg[6]  (.CP(CTS_2),
	.D(FE_PHN135_n_246),
	.Q(FE_PHN53_roi_reg_6));
   DFQD1 \roi_reg_reg[3]  (.CP(CTS_2),
	.D(n_237),
	.Q(FE_PHN54_roi_reg_3));
   DFQD1 \roi_reg_reg[10]  (.CP(CTS_2),
	.D(FE_PHN136_n_233),
	.Q(FE_PHN57_roi_reg_10));
   DFQD1 \roi_reg_reg[14]  (.CP(CTS_2),
	.D(n_228),
	.Q(FE_PHN60_roi_reg_14));
   DFQD1 \roi_reg_reg[7]  (.CP(CTS_2),
	.D(FE_PHN132_n_227),
	.Q(FE_PHN56_roi_reg_7));
   DFQD1 \roi_reg_reg[11]  (.CP(CTS_2),
	.D(n_231),
	.Q(FE_PHN55_roi_reg_11));
   AO211D1 p20591A1237 (.A1(n_248),
	.A2(FE_PHN31_state_1),
	.B(n_225),
	.C(n_247),
	.Z(FE_PHN126_n_249));
   AO222D1 p20740A1297 (.A1(n_244),
	.A2(roi_reg[6]),
	.B1(FE_PDN74_n_243),
	.B2(n_104),
	.C1(roi[6]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_246));
   AO222D1 p20740A36982006 (.A1(n_244),
	.A2(roi_reg[0]),
	.B1(FE_PDN74_n_243),
	.B2(n_111),
	.C1(roi[0]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_245));
   OAI211D1 p20299A2833 (.A1(n_240),
	.A2(l1acc),
	.B(n_223),
	.C(n_53),
	.ZN(n_241));
   AO222D1 p20740A36997547 (.A1(n_244),
	.A2(roi_reg[1]),
	.B1(FE_PDN74_n_243),
	.B2(n_109),
	.C1(roi[1]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(FE_PHN133_n_239));
   AO222D1 p20740A37007765 (.A1(n_244),
	.A2(roi_reg[2]),
	.B1(FE_PDN74_n_243),
	.B2(n_108),
	.C1(roi[2]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(FE_PHN131_n_238));
   AO222D1 p20740A37019867 (.A1(n_244),
	.A2(roi_reg[3]),
	.B1(FE_PDN74_n_243),
	.B2(n_110),
	.C1(roi[3]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_237));
   AO222D1 p20740A37023377 (.A1(n_244),
	.A2(roi_reg[4]),
	.B1(FE_PDN74_n_243),
	.B2(n_106),
	.C1(roi[4]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(FE_PHN138_n_236));
   AO222D1 p20740A37039719 (.A1(n_244),
	.A2(FE_PHN50_roi_reg_5),
	.B1(FE_PDN74_n_243),
	.B2(n_105),
	.C1(roi[5]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_235));
   AO222D1 p20740A37041591 (.A1(n_244),
	.A2(FE_PHN51_roi_reg_9),
	.B1(n_243),
	.B2(n_94),
	.C1(roi[9]),
	.C2(FE_OFN2_n_242),
	.Z(n_234));
   AO222D1 p20740A37056789 (.A1(n_244),
	.A2(roi_reg[10]),
	.B1(FE_PDN74_n_243),
	.B2(n_92),
	.C1(roi[10]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_233));
   AO222D1 p20740A37065927 (.A1(n_244),
	.A2(roi_reg[8]),
	.B1(n_243),
	.B2(n_93),
	.C1(roi[8]),
	.C2(FE_OFN2_n_242),
	.Z(n_232));
   AO222D1 p20740A37072001 (.A1(n_244),
	.A2(roi_reg[11]),
	.B1(FE_PDN74_n_243),
	.B2(n_91),
	.C1(roi[11]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_231));
   AO222D1 p20740A37081122 (.A1(n_244),
	.A2(FE_PHN58_roi_reg_12),
	.B1(FE_PDN74_n_243),
	.B2(n_59),
	.C1(roi[12]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(FE_PHN130_n_230));
   AO222D1 p20740A37092005 (.A1(n_244),
	.A2(roi_reg[13]),
	.B1(FE_PDN74_n_243),
	.B2(n_58),
	.C1(roi[13]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_229));
   AO222D1 p20740A37109771 (.A1(n_244),
	.A2(FE_PHN61_roi_reg_14),
	.B1(FE_PDN74_n_243),
	.B2(n_57),
	.C1(roi[14]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_228));
   AO222D1 p20740A37113457 (.A1(n_244),
	.A2(roi_reg[7]),
	.B1(FE_PDN74_n_243),
	.B2(n_103),
	.C1(roi[7]),
	.C2(FE_PDN73_FE_OFN2_n_242),
	.Z(n_227));
   AO22D0 p20703A1279 (.A1(n_244),
	.A2(FE_PHN30_n_407),
	.B1(FE_PDN73_FE_OFN2_n_242),
	.B2(roi[15]),
	.Z(n_226));
   OAI21D1 p20590A6179 (.A1(n_183),
	.A2(n_184),
	.B(n_244),
	.ZN(n_225));
   INR4D0 p21125A7837 (.A1(reset),
	.B1(FE_OFN2_n_242),
	.B2(n_248),
	.B3(n_219),
	.ZN(n_224));
   IAO21D1 p20300A37137557 (.A1(FE_PDN81_n_220),
	.A2(n_222),
	.B(n_182),
	.ZN(n_223));
   OAI21D1 p214748365A7654 (.A1(n_175),
	.A2(n_217),
	.B(n_214),
	.ZN(FE_OFN4_dout_15));
   OAI21D1 p214748365A37148867 (.A1(n_166),
	.A2(n_217),
	.B(FE_PDN77_n_212),
	.ZN(FE_PDN79_dout_29));
   OAI21D2 p214748365A37151377 (.A1(n_179),
	.A2(n_217),
	.B(n_214),
	.ZN(dout[27]));
   OAI21D1 p214748365A37163717 (.A1(n_174),
	.A2(n_217),
	.B(FE_PDN77_n_212),
	.ZN(FE_OFN12_dout_26));
   OAI21D2 p214748365A3717 (.A1(n_171),
	.A2(n_217),
	.B(n_214),
	.ZN(dout[25]));
   OAI21D2 p214748365A37184599 (.A1(n_169),
	.A2(n_217),
	.B(n_222),
	.ZN(FE_PDN82_dout_24));
   OAI21D2 p214748365A37193779 (.A1(n_173),
	.A2(n_217),
	.B(n_214),
	.ZN(dout[23]));
   OAI21D2 p214748365A37202007 (.A1(n_167),
	.A2(n_217),
	.B(n_222),
	.ZN(dout[22]));
   OAI21D2 p214748365A37211237 (.A1(n_165),
	.A2(n_217),
	.B(n_214),
	.ZN(dout[21]));
   OAI21D1 p214748365A37221297 (.A1(n_163),
	.A2(n_217),
	.B(n_222),
	.ZN(FE_OFN1_dout_20));
   OAI21D2 p214748365A37232006 (.A1(n_168),
	.A2(n_217),
	.B(n_214),
	.ZN(dout[19]));
   OAI21D2 p214748365A37242833 (.A1(n_180),
	.A2(n_217),
	.B(FE_PDN77_n_212),
	.ZN(dout[18]));
   OAI21D1 p214748365A37257547 (.A1(n_176),
	.A2(n_217),
	.B(FE_PDN77_n_212),
	.ZN(FE_OFN3_dout_16));
   NR2XD2 p20590A37267765 (.A1(n_243),
	.A2(FE_PDN73_FE_OFN2_n_242),
	.ZN(n_244));
   AO221D1 p214748365A37279867 (.A1(n_198),
	.A2(l1acc_id_reg[7]),
	.B1(n_158),
	.B2(n_197),
	.C(FE_PDN87_n_196),
	.Z(dout[7]));
   OAI21D1 p214748365A37283377 (.A1(n_172),
	.A2(n_217),
	.B(n_214),
	.ZN(FE_OFN6_dout_13));
   OAI21D2 p214748365A37299719 (.A1(n_170),
	.A2(n_217),
	.B(FE_PDN77_n_212),
	.ZN(FE_OFN7_dout_12));
   AO221D1 p214748365A37301591 (.A1(n_198),
	.A2(l1acc_id_reg[11]),
	.B1(FE_PDN142_n_152),
	.B2(n_197),
	.C(FE_PDN87_n_196),
	.Z(dout[11]));
   AO221D0 p214748365A37316789 (.A1(n_198),
	.A2(l1acc_id_reg[10]),
	.B1(n_150),
	.B2(n_197),
	.C(FE_PDN87_n_196),
	.Z(FE_PDN84_dout_10));
   AO221D1 p214748365A37325927 (.A1(n_198),
	.A2(l1acc_id_reg[9]),
	.B1(n_149),
	.B2(n_197),
	.C(FE_PDN87_n_196),
	.Z(dout[9]));
   MOAI22D0 p214748365A37332001 (.A1(n_162),
	.A2(n_217),
	.B1(n_198),
	.B2(l1acc_id_reg[8]),
	.ZN(FE_OFN8_dout_8));
   OAI21D1 p214748365A37341122 (.A1(n_159),
	.A2(n_217),
	.B(n_222),
	.ZN(FE_OFN5_dout_14));
   AO221D1 p214748365A37352005 (.A1(n_198),
	.A2(l1acc_id_reg[6]),
	.B1(n_147),
	.B2(n_197),
	.C(FE_PDN87_n_196),
	.Z(dout[6]));
   AO221D1 p214748365A37369771 (.A1(n_198),
	.A2(l1acc_id_reg[5]),
	.B1(n_153),
	.B2(n_197),
	.C(FE_PDN87_n_196),
	.Z(dout[5]));
   MOAI22D1 p214748365A37373457 (.A1(n_164),
	.A2(n_217),
	.B1(n_198),
	.B2(l1acc_id_reg[4]),
	.ZN(FE_OFN9_dout_4));
   AO221D1 p214748365A37381279 (.A1(n_198),
	.A2(l1acc_id_reg[3]),
	.B1(n_146),
	.B2(n_197),
	.C(n_196),
	.Z(dout[3]));
   AO221D1 p214748365A37396179 (.A1(n_198),
	.A2(l1acc_id_reg[2]),
	.B1(n_148),
	.B2(n_197),
	.C(FE_PDN71_n_196),
	.Z(dout[2]));
   AO221D1 p214748365A37407837 (.A1(n_198),
	.A2(l1acc_id_reg[1]),
	.B1(n_157),
	.B2(n_197),
	.C(n_196),
	.Z(dout[1]));
   AO221D1 p214748365A37417557 (.A1(n_198),
	.A2(l1acc_id_reg[0]),
	.B1(n_154),
	.B2(n_197),
	.C(FE_PDN71_n_196),
	.Z(dout[0]));
   INR3D0 p21125A37427654 (.A1(n_184),
	.B1(n_183),
	.B2(n_181),
	.ZN(n_219));
   MOAI22D1 p20298A8867 (.A1(n_184),
	.A2(n_217),
	.B1(n_181),
	.B2(n_197),
	.ZN(n_182));
   AN3XD1 p20589A1377 (.A1(n_181),
	.A2(n_98),
	.A3(n_184),
	.Z(FE_PHN122_n_243));
   AOI221D1 p214748365A37433717 (.A1(din0[18]),
	.A2(n_178),
	.B1(din1[18]),
	.B2(n_177),
	.C(n_130),
	.ZN(n_180));
   AOI221D4 p214748365A37444599 (.A1(din0[27]),
	.A2(n_178),
	.B1(din1[27]),
	.B2(n_177),
	.C(n_135),
	.ZN(n_179));
   AOI221D4 p214748365A37453779 (.A1(din0[16]),
	.A2(n_178),
	.B1(din1[16]),
	.B2(n_177),
	.C(n_129),
	.ZN(n_176));
   AOI221D4 p214748365A37462007 (.A1(din0[15]),
	.A2(n_178),
	.B1(din1[15]),
	.B2(n_177),
	.C(n_120),
	.ZN(n_175));
   AOI221D4 p214748365A37471237 (.A1(din0[26]),
	.A2(n_178),
	.B1(din1[26]),
	.B2(n_177),
	.C(n_127),
	.ZN(n_174));
   AOI221D4 p214748365A37481297 (.A1(din0[23]),
	.A2(n_178),
	.B1(din1[23]),
	.B2(n_177),
	.C(n_122),
	.ZN(n_173));
   AOI221D4 p214748365A37492006 (.A1(din0[13]),
	.A2(n_178),
	.B1(din1[13]),
	.B2(n_177),
	.C(n_126),
	.ZN(n_172));
   AOI221D4 p214748365A37502833 (.A1(din0[25]),
	.A2(n_178),
	.B1(din1[25]),
	.B2(n_177),
	.C(n_125),
	.ZN(n_171));
   AOI221D1 p214748365A37517547 (.A1(din0[12]),
	.A2(n_178),
	.B1(din1[12]),
	.B2(n_177),
	.C(n_124),
	.ZN(n_170));
   AOI221D4 p214748365A37527765 (.A1(din0[24]),
	.A2(n_178),
	.B1(din1[24]),
	.B2(n_177),
	.C(n_123),
	.ZN(n_169));
   AOI221D4 p214748365A37539867 (.A1(din0[19]),
	.A2(n_178),
	.B1(din1[19]),
	.B2(n_177),
	.C(n_116),
	.ZN(n_168));
   AOI221D1 p214748365A37543377 (.A1(din0[22]),
	.A2(n_178),
	.B1(din1[22]),
	.B2(n_177),
	.C(n_117),
	.ZN(n_167));
   AOI221D4 p214748365A37559719 (.A1(din0[29]),
	.A2(n_178),
	.B1(din1[29]),
	.B2(n_177),
	.C(n_115),
	.ZN(n_166));
   AOI221D2 p214748365A37561591 (.A1(din0[21]),
	.A2(n_178),
	.B1(din1[21]),
	.B2(n_177),
	.C(n_118),
	.ZN(n_165));
   AOI221D4 p214748365A37576789 (.A1(din0[4]),
	.A2(n_178),
	.B1(din1[4]),
	.B2(n_177),
	.C(n_119),
	.ZN(n_164));
   AOI221D1 p214748365A37585927 (.A1(din0[20]),
	.A2(n_178),
	.B1(din1[20]),
	.B2(n_177),
	.C(n_136),
	.ZN(n_163));
   AOI221D4 p214748365A37592001 (.A1(din0[8]),
	.A2(n_178),
	.B1(din1[8]),
	.B2(n_177),
	.C(n_121),
	.ZN(n_162));
   AOI21D2 p214748365A37601122 (.A1(n_134),
	.A2(n_133),
	.B(n_217),
	.ZN(dout[28]));
   AOI21D2 p214748365A37612005 (.A1(n_131),
	.A2(n_132),
	.B(n_217),
	.ZN(dout[17]));
   AOI221D1 p214748365A37629771 (.A1(din0[14]),
	.A2(n_178),
	.B1(din1[14]),
	.B2(n_177),
	.C(n_113),
	.ZN(n_159));
   AO221D1 p214748365A37633457 (.A1(din2[7]),
	.A2(n_156),
	.B1(din3[7]),
	.B2(n_155),
	.C(n_142),
	.Z(n_158));
   AO221D0 p214748365A37641279 (.A1(din2[1]),
	.A2(n_156),
	.B1(din3[1]),
	.B2(n_155),
	.C(n_138),
	.Z(n_157));
   AO221D0 p214748365A37656179 (.A1(din2[0]),
	.A2(n_156),
	.B1(din3[0]),
	.B2(n_155),
	.C(n_128),
	.Z(n_154));
   AO221D0 p214748365A37667837 (.A1(din2[5]),
	.A2(n_156),
	.B1(din3[5]),
	.B2(n_155),
	.C(n_144),
	.Z(n_153));
   AO221D0 p214748365A37677557 (.A1(din2[11]),
	.A2(n_156),
	.B1(din3[11]),
	.B2(n_155),
	.C(FE_PDN86_n_137),
	.Z(n_152));
   NR2D1 p21349A7654 (.A1(FE_PDN81_n_220),
	.A2(n_151),
	.ZN(n_247));
   ND4D2 p20301A8867 (.A1(n_112),
	.A2(n_107),
	.A3(n_95),
	.A4(n_60),
	.ZN(n_181));
   AO221D1 p214748365A37681377 (.A1(din2[10]),
	.A2(n_156),
	.B1(din3[10]),
	.B2(n_155),
	.C(n_140),
	.Z(n_150));
   AO221D0 p214748365A37693717 (.A1(din2[9]),
	.A2(n_156),
	.B1(din3[9]),
	.B2(n_155),
	.C(n_143),
	.Z(n_149));
   AO221D0 p214748365A37704599 (.A1(din2[2]),
	.A2(n_156),
	.B1(din3[2]),
	.B2(n_155),
	.C(n_139),
	.Z(n_148));
   AO221D0 p214748365A37713779 (.A1(din2[6]),
	.A2(n_156),
	.B1(din3[6]),
	.B2(n_155),
	.C(n_141),
	.Z(n_147));
   AO221D0 p214748365A37722007 (.A1(din2[3]),
	.A2(n_156),
	.B1(din3[3]),
	.B2(n_155),
	.C(n_114),
	.Z(n_146));
   DFKCNQD1 \bcid_reg_reg[11]  (.CN(n_102),
	.CP(CTS_2),
	.D(n_145),
	.Q(FE_PHN107_bcid_reg_11));
   AO22D0 p214748365A37761237 (.A1(din0[5]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[5]),
	.Z(n_144));
   AO22D1 p214748365A37771297 (.A1(din0[9]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[9]),
	.Z(n_143));
   AO22D0 p214748365A37782006 (.A1(din0[7]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[7]),
	.Z(n_142));
   AO22D0 p214748365A3779 (.A1(din0[6]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[6]),
	.Z(n_141));
   AO22D0 p214748365A37802833 (.A1(din0[10]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[10]),
	.Z(n_140));
   AO22D0 p214748365A37817547 (.A1(din0[2]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[2]),
	.Z(n_139));
   AO22D0 p214748365A37827765 (.A1(din0[1]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[1]),
	.Z(n_138));
   AO22D0 p214748365A37839867 (.A1(din0[11]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[11]),
	.Z(n_137));
   AO22D0 p214748365A37843377 (.A1(din2[20]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[20]),
	.Z(n_136));
   AO22D0 p214748365A37859719 (.A1(din2[27]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[27]),
	.Z(n_135));
   AOI22D1 p214748365A37861591 (.A1(din0[28]),
	.A2(n_178),
	.B1(din1[28]),
	.B2(n_177),
	.ZN(n_134));
   AOI22D2 p214748365A37876789 (.A1(din2[28]),
	.A2(n_156),
	.B1(din3[28]),
	.B2(n_155),
	.ZN(n_133));
   AOI22D1 p214748365A37885927 (.A1(din2[17]),
	.A2(n_156),
	.B1(din3[17]),
	.B2(n_155),
	.ZN(n_132));
   AOI22D1 p214748365A37892001 (.A1(din0[17]),
	.A2(n_178),
	.B1(din1[17]),
	.B2(n_177),
	.ZN(n_131));
   AO22D0 p214748365A37901122 (.A1(din2[18]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[18]),
	.Z(n_130));
   AO22D0 p214748365A37912005 (.A1(din2[16]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[16]),
	.Z(n_129));
   NR4D0 p20384A9771 (.A1(n_177),
	.A2(n_156),
	.A3(n_96),
	.A4(n_55),
	.ZN(n_220));
   AO22D0 p214748365A37923457 (.A1(din0[0]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[0]),
	.Z(n_128));
   AO22D1 p214748365A37931279 (.A1(din2[26]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[26]),
	.Z(n_127));
   AO22D1 p214748365A37946179 (.A1(din2[13]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[13]),
	.Z(n_126));
   AO22D0 p214748365A37957837 (.A1(din2[25]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[25]),
	.Z(n_125));
   AO22D0 p214748365A37967557 (.A1(din2[12]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[12]),
	.Z(n_124));
   AO22D0 p214748365A37977654 (.A1(din2[24]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[24]),
	.Z(n_123));
   AO22D0 p214748365A37988867 (.A1(din2[23]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[23]),
	.Z(n_122));
   AO22D0 p214748365A37991377 (.A1(din2[8]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[8]),
	.Z(n_121));
   AO22D0 p214748365A38003717 (.A1(din2[15]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[15]),
	.Z(n_120));
   AO22D0 p214748365A38014599 (.A1(din2[4]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[4]),
	.Z(n_119));
   AO22D0 p214748365A38023779 (.A1(din2[21]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[21]),
	.Z(n_118));
   AO22D0 p214748365A38032007 (.A1(din2[22]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[22]),
	.Z(n_117));
   AO22D0 p214748365A38041237 (.A1(din2[19]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[19]),
	.Z(n_116));
   AO22D0 p214748365A38051297 (.A1(din2[29]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[29]),
	.Z(n_115));
   AO22D0 p214748365A38062006 (.A1(din0[3]),
	.A2(n_178),
	.B1(n_177),
	.B2(din1[3]),
	.Z(n_114));
   AO22D0 p214748365A38072833 (.A1(din2[14]),
	.A2(n_156),
	.B1(n_155),
	.B2(din3[14]),
	.Z(n_113));
   DFKCNQD1 \bcid_reg_reg[8]  (.CN(n_100),
	.CP(CTS_2),
	.D(n_145),
	.Q(FE_PHN15_bcid_reg_8));
   NR4D0 p20404A7547 (.A1(n_111),
	.A2(n_110),
	.A3(n_109),
	.A4(n_108),
	.ZN(n_112));
   NR4D0 p20299A38107765 (.A1(n_106),
	.A2(n_105),
	.A3(n_104),
	.A4(n_103),
	.ZN(n_107));
   XOR2D1 p22133A9867 (.A1(n_83),
	.A2(bcid_reg[11]),
	.Z(n_102));
   DFKCNQD1 \bcid_reg_reg[4]  (.CN(n_79),
	.CP(CTS_2),
	.D(n_145),
	.Q(FE_PHN109_bcid_reg_4));
   XOR2D1 p22582A3377 (.A1(n_76),
	.A2(FE_PDN141_addr_5),
	.Z(n_101));
   HA1D0 p22266A9719 (.A(bcid_reg[8]),
	.B(FE_PDN70_n_66),
	.CO(n_99),
	.S(n_100));
   CKND1 p20893A (.I(n_183),
	.ZN(n_98));
   IND2D4 p214748365A38121591 (.A1(n_96),
	.B1(n_68),
	.ZN(n_178));
   CKND2D3 p20559A6789 (.A1(n_75),
	.A2(n_65),
	.ZN(n_156));
   NR4D0 p20493A5927 (.A1(n_94),
	.A2(n_93),
	.A3(n_92),
	.A4(n_91),
	.ZN(n_95));
   CKND2D4 p20384A38162001 (.A1(n_70),
	.A2(n_61),
	.ZN(n_177));
   XNR2D1 p20405A1122 (.A1(roi_reg[2]),
	.A2(n_88),
	.ZN(n_108));
   CKXOR2D1 p20310A2005 (.A1(FE_PHN50_roi_reg_5),
	.A2(n_85),
	.Z(n_105));
   IND4D1 p21705A9771 (.A1(FE_PHN99_state_0),
	.B1(reset),
	.B2(n_90),
	.B3(state[1]),
	.ZN(n_151));
   ND4D1 p20895A3457 (.A1(reset),
	.A2(n_90),
	.A3(state[1]),
	.A4(FE_PHN99_state_0),
	.ZN(n_183));
   ND4D8 p214748365A38171279 (.A1(n_88),
	.A2(n_64),
	.A3(n_69),
	.A4(n_22),
	.ZN(roe[2]));
   XOR2D1 p22618A6179 (.A1(n_56),
	.A2(addr[7]),
	.Z(n_87));
   OR4D1 p214748365A38187837 (.A1(n_25),
	.A2(n_73),
	.A3(n_85),
	.A4(FE_PDN78_n_74),
	.Z(roe[1]));
   NR2XD0 p22285A7557 (.A1(n_82),
	.A2(n_81),
	.ZN(n_84));
   NR3D0 p22135A7654 (.A1(n_82),
	.A2(n_81),
	.A3(n_80),
	.ZN(n_83));
   HA1D0 p22638A8867 (.A(bcid_reg[4]),
	.B(n_32),
	.CO(n_78),
	.S(n_79));
   HA1D0 p22581A1377 (.A(FE_PDN63_addr_4),
	.B(n_33),
	.CO(n_76),
	.S(n_77));
   NR2XD0 p20559A38193717 (.A1(n_52),
	.A2(FE_PDN78_n_74),
	.ZN(n_75));
   IND3D1 p20895A38204599 (.A1(n_73),
	.B1(n_88),
	.B2(n_67),
	.ZN(n_96));
   INR2D1 p21761A3779 (.A1(reset),
	.B1(n_90),
	.ZN(n_248));
   XOR2D1 p22681A2007 (.A1(n_43),
	.A2(addr[6]),
	.Z(n_72));
   XOR2D1 p22866A1237 (.A1(n_46),
	.A2(FE_PDN65_addr_3),
	.Z(n_71));
   NR2D1 p20426A1297 (.A1(n_50),
	.A2(n_85),
	.ZN(n_70));
   DFKCNQD1 \bcid_reg_reg[2]  (.CN(n_45),
	.CP(CTS_2),
	.D(n_145),
	.Q(FE_PHN24_bcid_reg_2));
   EDFQD1 \l1acc_id_reg_reg[2]  (.CP(CTS_2),
	.D(bcid_reg[2]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[2]));
   EDFQD1 \stop_reg_reg[4]  (.CP(CTS_2),
	.D(FE_PDN63_addr_4),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[4]));
   EDFQD1 \l1acc_id_reg_reg[8]  (.CP(CTS_2),
	.D(bcid_reg[8]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[8]));
   EDFQD1 \stop_reg_reg[7]  (.CP(CTS_2),
	.D(addr[7]),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[7]));
   EDFQD1 \l1acc_id_reg_reg[6]  (.CP(CTS_2),
	.D(bcid_reg[6]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[6]));
   EDFQD1 \l1acc_id_reg_reg[11]  (.CP(CTS_2),
	.D(bcid_reg[11]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[11]));
   EDFQD1 \l1acc_id_reg_reg[4]  (.CP(CTS_2),
	.D(bcid_reg[4]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[4]));
   XNR2D1 p20594A2006 (.A1(roi_reg[10]),
	.A2(n_69),
	.ZN(n_92));
   XNR2D1 p20476A2833 (.A1(roi_reg[0]),
	.A2(n_68),
	.ZN(n_111));
   XNR2D1 p20545A7547 (.A1(roi_reg[3]),
	.A2(n_67),
	.ZN(n_110));
   INVD1 p22113A (.I(FE_PDN70_n_66),
	.ZN(n_82));
   CKXOR2D1 p20588A7765 (.A1(n_73),
	.A2(roi_reg[1]),
	.Z(n_109));
   XNR2D1 p20485A9867 (.A1(roi_reg[8]),
	.A2(n_65),
	.ZN(n_93));
   XNR2D1 p20510A3377 (.A1(roi_reg[6]),
	.A2(n_64),
	.ZN(n_104));
   EDFQD1 \l1acc_id_reg_reg[10]  (.CP(CTS_2),
	.D(FE_PHN18_bcid_reg_10),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[10]));
   EDFQD1 \l1acc_id_reg_reg[3]  (.CP(CTS_2),
	.D(bcid_reg[3]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[3]));
   EDFQD1 \stop_reg_reg[5]  (.CP(CTS_2),
	.D(FE_PDN67_addr_5),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[5]));
   EDFQD1 \stop_reg_reg[6]  (.CP(CTS_2),
	.D(addr[6]),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[6]));
   EDFQD1 \l1acc_id_reg_reg[5]  (.CP(CTS_2),
	.D(bcid_reg[5]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[5]));
   EDFQD1 \l1acc_id_reg_reg[7]  (.CP(CTS_2),
	.D(bcid_reg[7]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[7]));
   EDFQD1 \l1acc_id_reg_reg[1]  (.CP(CTS_2),
	.D(bcid_reg[1]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[1]));
   EDFQD1 \l1acc_id_reg_reg[0]  (.CP(CTS_2),
	.D(bcid_reg[0]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[0]));
   EDFQD1 \l1acc_id_reg_reg[9]  (.CP(CTS_2),
	.D(bcid_reg[9]),
	.E(FE_OFN2_n_242),
	.Q(l1acc_id_reg[9]));
   EDFQD1 \stop_reg_reg[2]  (.CP(CTS_2),
	.D(addr[2]),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[2]));
   EDFQD1 \stop_reg_reg[1]  (.CP(CTS_2),
	.D(FE_PDN139_addr_1),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[1]));
   EDFQD1 \stop_reg_reg[0]  (.CP(CTS_2),
	.D(addr[0]),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[0]));
   IND4D2 p214748365A38419719 (.A1(n_407),
	.B1(n_67),
	.B2(n_54),
	.B3(n_51),
	.ZN(FE_OFN10_roe_3));
   IND4D1 p214748365A38421591 (.A1(FE_PDN76_n_29),
	.B1(n_68),
	.B2(n_61),
	.B3(n_65),
	.ZN(FE_OFN11_roe_0));
   EDFQD1 \stop_reg_reg[3]  (.CP(CTS_2),
	.D(FE_PHN62_addr_3),
	.E(FE_OFN2_n_242),
	.Q(stop_reg[3]));
   NR3D0 p21186A6789 (.A1(n_59),
	.A2(n_58),
	.A3(n_57),
	.ZN(n_60));
   INR3D0 p22619A5927 (.A1(addr[6]),
	.B1(n_41),
	.B2(n_42),
	.ZN(n_56));
   CKND2D1 p20935A2001 (.A1(n_68),
	.A2(n_36),
	.ZN(n_55));
   XNR2D1 p20580A1122 (.A1(roi_reg[7]),
	.A2(n_54),
	.ZN(n_103));
   IND4D1 p20407A2005 (.A1(roi_reg[3]),
	.B1(n_27),
	.B2(n_34),
	.B3(roi_reg[2]),
	.ZN(n_88));
   ND4D1 p21376A9771 (.A1(n_31),
	.A2(n_217),
	.A3(n_214),
	.A4(n_53),
	.ZN(n_90));
   NR4D1 p21435A3457 (.A1(n_28),
	.A2(n_21),
	.A3(n_11),
	.A4(n_10),
	.ZN(n_184));
   CKND2D1 p20560A1279 (.A1(n_69),
	.A2(n_51),
	.ZN(n_52));
   CKND2D1 p20530A6179 (.A1(n_64),
	.A2(n_54),
	.ZN(n_50));
   XNR2D1 p20657A7837 (.A1(roi_reg[11]),
	.A2(n_51),
	.ZN(n_91));
   CKXOR2D1 p20580A38447557 (.A1(FE_PHN51_roi_reg_9),
	.A2(FE_PDN78_n_74),
	.Z(n_94));
   XNR2D1 p20596A7654 (.A1(roi_reg[4]),
	.A2(n_61),
	.ZN(n_106));
   NR4D0 p22112A8867 (.A1(n_39),
	.A2(n_38),
	.A3(n_49),
	.A4(n_48),
	.ZN(n_66));
   INR4D1 p20301A38451377 (.A1(FE_PHN50_roi_reg_5),
	.B1(roi_reg[7]),
	.B2(roi_reg[6]),
	.B3(n_26),
	.ZN(n_85));
   HA1D0 p22866A38463717 (.A(addr[2]),
	.B(n_24),
	.CO(n_46),
	.S(n_47));
   HA1D0 p22967A4599 (.A(bcid_reg[2]),
	.B(n_23),
	.CO(n_44),
	.S(n_45));
   NR2XD0 p22682A3779 (.A1(n_42),
	.A2(n_41),
	.ZN(n_43));
   NR2XD0 p22737A2007 (.A1(n_39),
	.A2(n_38),
	.ZN(n_40));
   NR3D0 p22676A1237 (.A1(n_39),
	.A2(n_38),
	.A3(n_49),
	.ZN(n_37));
   IND4D1 p20513A1297 (.A1(roi_reg[7]),
	.B1(n_36),
	.B2(FE_PDN75_n_35),
	.B3(roi_reg[6]),
	.ZN(n_64));
   AN4XD1 p20587A2006 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.A3(n_34),
	.A4(n_8),
	.Z(n_73));
   IND4D1 p20489A2833 (.A1(roi_reg[9]),
	.B1(n_36),
	.B2(n_5),
	.B3(roi_reg[8]),
	.ZN(n_65));
   IND3D1 p20564A7547 (.A1(FE_PDN69_roi_reg_11),
	.B1(roi_reg[10]),
	.B2(n_36),
	.ZN(n_69));
   CKND1 p22557A (.I(n_42),
	.ZN(n_33));
   CKND1 p22610A (.I(n_39),
	.ZN(n_32));
   DFKCNQD1 \bcid_reg_reg[1]  (.CN(n_20),
	.CP(CTS_2),
	.D(n_145),
	.Q(FE_PHN29_bcid_reg_1));
   ND4D1 p20548A7765 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.A3(n_34),
	.A4(roi_reg[3]),
	.ZN(n_67));
   ND4D2 p20479A9867 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.A3(n_34),
	.A4(n_6),
	.ZN(n_68));
   NR2D1 p21440A3377 (.A1(n_198),
	.A2(we),
	.ZN(n_31));
   CKXOR2D1 p21193A9719 (.A1(FE_PHN58_roi_reg_12),
	.A2(n_29),
	.Z(n_59));
   INR4D0 p20575A1591 (.A1(roi_reg[9]),
	.B1(roi_reg[11]),
	.B2(roi_reg[10]),
	.B3(n_155),
	.ZN(n_74));
   ND3D1 p20597A6789 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.A3(n_7),
	.ZN(n_61));
   ND3D1 p20531A5927 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.A3(roi_reg[7]),
	.ZN(n_54));
   ND2D1 p20565A2001 (.A1(n_36),
	.A2(roi_reg[11]),
	.ZN(n_51));
   AN3XD1 p21082A1122 (.A1(l1acc),
	.A2(reset),
	.A3(we),
	.Z(n_242));
   ND4D1 p21436A2005 (.A1(n_16),
	.A2(n_15),
	.A3(n_14),
	.A4(n_13),
	.ZN(n_28));
   AN2XD1 p20404A38489771 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.Z(n_27));
   CKND2D1 p20305A3457 (.A1(n_36),
	.A2(FE_PDN75_n_35),
	.ZN(n_26));
   CKXOR2D1 p21260A1279 (.A1(n_25),
	.A2(roi_reg[13]),
	.Z(n_58));
   ND3D1 p22556A6179 (.A1(n_24),
	.A2(FE_PDN65_addr_3),
	.A3(addr[2]),
	.ZN(n_42));
   ND3D1 p22129A7837 (.A1(n_23),
	.A2(bcid_reg[2]),
	.A3(bcid_reg[3]),
	.ZN(n_39));
   NR2D0 p214748365A38497557 (.A1(n_198),
	.A2(FE_PDN71_n_196),
	.ZN(n_212));
   XNR2D1 p21381A7654 (.A1(roi_reg[14]),
	.A2(n_22),
	.ZN(n_57));
   INVD1 p21623A (.I(n_198),
	.ZN(n_222));
   CKND2D1 p21519A8867 (.A1(n_17),
	.A2(n_9),
	.ZN(n_21));
   INVD1 p21552A (.I(n_217),
	.ZN(n_197));
   HA1D0 p22129A38501377 (.A(bcid_reg[1]),
	.B(bcid_reg[0]),
	.CO(n_23),
	.S(n_20));
   HA1D0 p22557A38513717 (.A(addr[0]),
	.B(addr[1]),
	.CO(n_24),
	.S(n_19));
   INVD1 p21944A (.I(we),
	.ZN(n_240));
   INVD1 p21296A (.I(FE_PDN71_n_196),
	.ZN(n_214));
   AN3D2 p21448A4599 (.A1(n_12),
	.A2(n_18),
	.A3(state[1]),
	.Z(n_198));
   CKND2 p20113A (.I(n_155),
	.ZN(n_36));
   OR3D4 p21314A3779 (.A1(FE_PHN93_state_2),
	.A2(n_4),
	.A3(n_18),
	.Z(n_217));
   XNR2D1 p21523A2007 (.A1(stop_reg[5]),
	.A2(FE_PDN67_addr_5),
	.ZN(n_17));
   XNR2D1 p21454A1237 (.A1(stop_reg[3]),
	.A2(FE_PDN65_addr_3),
	.ZN(n_16));
   XNR2D1 p21443A1297 (.A1(addr[2]),
	.A2(stop_reg[2]),
	.ZN(n_15));
   XNR2D1 p21436A38532006 (.A1(stop_reg[1]),
	.A2(FE_PDN139_addr_1),
	.ZN(n_14));
   XNR2D1 p21439A2833 (.A1(stop_reg[0]),
	.A2(addr[0]),
	.ZN(n_13));
   OR3D1 p21809A7547 (.A1(FE_PHN99_state_0),
	.A2(state[1]),
	.A3(FE_PHN93_state_2),
	.Z(n_53));
   INR3D4 p21571A7765 (.A1(FE_PHN99_state_0),
	.B1(state[1]),
	.B2(FE_PHN93_state_2),
	.ZN(we));
   NR3D1 p21296A38549867 (.A1(n_12),
	.A2(FE_PHN99_state_0),
	.A3(state[1]),
	.ZN(n_196));
   OR4D4 p20107A3377 (.A1(FE_PHN58_roi_reg_12),
	.A2(roi_reg[13]),
	.A3(FE_PDN72_roi_reg_14),
	.A4(n_407),
	.Z(n_155));
   CKXOR2D1 p21613A9719 (.A1(addr[6]),
	.A2(stop_reg[6]),
	.Z(n_11));
   CKXOR2D1 p21611A1591 (.A1(addr[7]),
	.A2(stop_reg[7]),
	.Z(n_10));
   XNR2D1 p21519A38556789 (.A1(FE_PDN63_addr_4),
	.A2(stop_reg[4]),
	.ZN(n_9));
   INR3D0 p21058A5927 (.A1(roi_reg[1]),
	.B1(roi_reg[3]),
	.B2(roi_reg[2]),
	.ZN(n_8));
   INR4D0 p21021A2001 (.A1(roi_reg[4]),
	.B1(roi_reg[6]),
	.B2(roi_reg[7]),
	.B3(FE_PHN50_roi_reg_5),
	.ZN(n_7));
   INR4D0 p20857A1122 (.A1(roi_reg[0]),
	.B1(roi_reg[2]),
	.B2(roi_reg[3]),
	.B3(roi_reg[1]),
	.ZN(n_6));
   INR4D0 p21193A38562005 (.A1(FE_PHN58_roi_reg_12),
	.B1(roi_reg[14]),
	.B2(n_407),
	.B3(roi_reg[13]),
	.ZN(n_29));
   INR3D1 p21260A38579771 (.A1(roi_reg[13]),
	.B1(n_407),
	.B2(FE_PDN72_roi_reg_14),
	.ZN(n_25));
   NR4D1 p20587A38583457 (.A1(roi_reg[4]),
	.A2(FE_PHN50_roi_reg_5),
	.A3(roi_reg[6]),
	.A4(roi_reg[7]),
	.ZN(n_34));
   NR4D1 p20514A1279 (.A1(FE_PHN51_roi_reg_9),
	.A2(roi_reg[8]),
	.A3(roi_reg[10]),
	.A4(FE_PDN69_roi_reg_11),
	.ZN(n_35));
   NR2XD0 p21068A6179 (.A1(roi_reg[10]),
	.A2(FE_PDN69_roi_reg_11),
	.ZN(n_5));
   CKND2D1 p23002A7837 (.A1(bcid_reg[9]),
	.A2(bcid_reg[8]),
	.ZN(n_81));
   CKND2D1 p22970A7557 (.A1(FE_PDN141_addr_5),
	.A2(addr[4]),
	.ZN(n_41));
   IND2D1 p21381A38597654 (.A1(n_407),
	.B1(roi_reg[14]),
	.ZN(n_22));
   CKND2D1 p22479A8867 (.A1(bcid_reg[5]),
	.A2(bcid_reg[4]),
	.ZN(n_38));
   INVD1 p21839A (.I(bc0),
	.ZN(n_145));
   AOI31D2 g21377 (.A1(n_222),
	.A2(n_240),
	.A3(n_217),
	.B(n_257),
	.ZN(FE_PHN125_n_409));
   OR3XD1 g38633717 (.A1(n_410),
	.A2(n_248),
	.A3(n_219),
	.Z(n_411));
   INR2D1 g34599 (.A1(FE_PDN81_n_220),
	.B1(n_151),
	.ZN(n_410));
   DFD1 \state_reg[1]  (.CP(CTS_2),
	.D(n_249),
	.Q(FE_PHN100_state_1),
	.QN(n_4));
   EDFKCND1 \bcid_reg_reg[9]  (.CN(n_145),
	.CP(CTS_2),
	.D(n_3),
	.E(n_99),
	.Q(FE_PHN19_bcid_reg_9),
	.QN(FE_PHN118_n_3));
   EDFKCND1 \bcid_reg_reg[5]  (.CN(n_145),
	.CP(CTS_2),
	.D(n_2),
	.E(n_78),
	.Q(FE_PHN27_bcid_reg_5),
	.QN(FE_PHN22_n_2));
   DFD1 \state_reg[2]  (.CP(CTS_2),
	.D(FE_PHN124_n_411),
	.Q(state[2]),
	.QN(n_12));
   EDFKCND1 \bcid_reg_reg[6]  (.CN(n_145),
	.CP(CTS_2),
	.D(n_49),
	.E(n_40),
	.Q(FE_PHN17_bcid_reg_6),
	.QN(FE_PHN33_n_49));
   EDFKCND1 \bcid_reg_reg[3]  (.CN(n_145),
	.CP(CTS_2),
	.D(n_1),
	.E(n_44),
	.Q(FE_PHN108_bcid_reg_3),
	.QN(FE_PHN21_n_1));
   DFKCND1 \bcid_reg_reg[0]  (.CN(n_0),
	.CP(CTS_2),
	.D(n_145),
	.Q(FE_PHN28_bcid_reg_0),
	.QN(FE_PHN14_n_0));
   EDFKCND1 \bcid_reg_reg[7]  (.CN(n_145),
	.CP(CTS_2),
	.D(FE_PHN119_n_48),
	.E(n_37),
	.Q(FE_PHN16_bcid_reg_7),
	.QN(FE_PHN34_n_48));
   DFD1 \state_reg[0]  (.CP(CTS_2),
	.D(FE_PHN123_n_250),
	.Q(state[0]),
	.QN(n_18));
   EDFKCND1 \bcid_reg_reg[10]  (.CN(n_145),
	.CP(CTS_2),
	.D(n_80),
	.E(n_84),
	.Q(bcid_reg[10]),
	.QN(FE_PHN111_n_80));
endmodule

