/*
###############################################################
#  Generated by:      Cadence Innovus 16.20-p002_1
#  OS:                Linux x86_64(Host ID hepasic2.physics.smu.edu)
#  Generated on:      Fri Jul  5 22:48:41 2019
#  Design:            DMRO
#  Command:           saveNetlist ../output/export.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jul  5 2019 22:39:57 CDT (Jul  6 2019 03:39:57 UTC)
// Verification Directory fv/DMRO 
module SER32b (
	CLKBit, 
	RSTn, 
	DataIn, 
	CLKWord, 
	DataOut, 
	FE_OFN0_rst_int);
   input CLKBit;
   input RSTn;
   input [31:0] DataIn;
   output CLKWord;
   output DataOut;
   input FE_OFN0_rst_int;

   // Internal wires
   wire FE_PHN346_FE_DBTN0_n_394;
   wire FE_PHN345_n_394;
   wire FE_PHN344_n_400;
   wire FE_PHN343_In_reg_6;
   wire FE_PHN342_In_reg_26;
   wire FE_PHN341_In_reg_12;
   wire FE_PHN340_In_reg_0;
   wire FE_PHN339_In_reg_2;
   wire FE_PHN338_FE_DBTN0_n_394;
   wire FE_PHN337_In_reg_15;
   wire FE_PHN336_n_394;
   wire FE_PHN335_In_reg_23;
   wire FE_PHN334_n_394;
   wire FE_PHN333_n_394;
   wire FE_PHN332_In_reg_17;
   wire FE_PHN331_n_394;
   wire FE_PHN330_n_394;
   wire FE_PHN329_In_reg_21;
   wire FE_PHN328_In_reg_28;
   wire FE_PHN327_In_reg_22;
   wire FE_PHN326_In_reg_0;
   wire FE_PHN325_In_reg_18;
   wire FE_PHN324_In_reg_14;
   wire FE_PHN323_In_reg_27;
   wire FE_PHN322_In_reg_1;
   wire FE_PHN321_In_reg_25;
   wire FE_PHN320_In_reg_9;
   wire FE_PHN319_In_reg_16;
   wire FE_PHN318_In_reg_26;
   wire FE_PHN317_In_reg_12;
   wire FE_PHN316_In_reg_8;
   wire FE_PHN315_In_reg_24;
   wire FE_PHN314_In_reg_6;
   wire FE_PHN313_In_reg_3;
   wire FE_PHN312_n_163;
   wire FE_PHN311_In_reg_7;
   wire FE_PHN310_In_reg_5;
   wire FE_PHN309_counter_0;
   wire FE_PHN308_n_400;
   wire FE_PHN307_counter_2;
   wire FE_PHN306_counter_1;
   wire FE_PHN305_n_399;
   wire FE_PHN304_n_394;
   wire FE_PHN303_n_163;
   wire FE_PHN302_counter_3;
   wire FE_PHN301_counter_0;
   wire FE_PHN300_n_407;
   wire FE_PHN299_In_reg_4;
   wire FE_PHN298_In_reg_11;
   wire FE_PHN297_In_reg_19;
   wire FE_PHN296_In_reg_29;
   wire FE_PHN295_In_reg_30;
   wire FE_PHN294_In_reg_20;
   wire FE_PHN293_In_reg_10;
   wire FE_PHN292_In_reg_25;
   wire FE_PHN291_In_reg_15;
   wire FE_PHN290_In_reg_13;
   wire FE_PHN289_In_reg_27;
   wire FE_PHN288_In_reg_14;
   wire FE_PHN287_In_reg_18;
   wire FE_PHN286_In_reg_28;
   wire FE_PHN285_In_reg_9;
   wire FE_PHN284_In_reg_3;
   wire FE_PHN283_In_reg_21;
   wire FE_PHN282_In_reg_22;
   wire FE_PHN281_In_reg_0;
   wire FE_PHN280_In_reg_1;
   wire FE_PHN279_In_reg_26;
   wire FE_PHN278_In_reg_5;
   wire FE_PHN277_In_reg_16;
   wire FE_PHN276_In_reg_12;
   wire FE_PHN275_In_reg_8;
   wire FE_PHN274_In_reg_23;
   wire FE_PHN273_In_reg_24;
   wire FE_PHN272_In_reg_6;
   wire FE_PHN271_In_reg_7;
   wire FE_PHN270_counter_1;
   wire FE_PHN269_In_reg_17;
   wire FE_PHN268_n_410;
   wire FE_PHN267_n_394;
   wire FE_PHN266_n_399;
   wire FE_PHN265_n_390;
   wire FE_PHN264_counter_3;
   wire FE_PHN263_n_405;
   wire FE_PHN262_n_0;
   wire FE_PHN261_counter_2;
   wire FE_PHN260_In_reg_2;
   wire FE_PHN259_In_reg_4;
   wire FE_PHN258_In_reg_20;
   wire FE_PHN257_In_reg_11;
   wire FE_PHN256_In_reg_10;
   wire FE_PHN255_In_reg_19;
   wire FE_PHN254_n_399;
   wire FE_PHN253_counter_1;
   wire FE_PHN252_n_163;
   wire FE_PSN250_counter_3;
   wire FE_PHN249_n_407;
   wire FE_PHN248_n_394;
   wire FE_PHN247_n_407;
   wire FE_PHN245_In_reg_29;
   wire FE_PHN244_n_407;
   wire FE_PHN243_n_201;
   wire FE_PHN242_n_394;
   wire FE_PHN241_n_394;
   wire FE_PHN240_n_394;
   wire FE_PHN239_n_394;
   wire FE_PHN238_n_394;
   wire FE_PHN237_n_394;
   wire FE_PHN236_n_394;
   wire FE_PHN235_n_394;
   wire FE_PHN234_n_394;
   wire FE_PHN232_n_394;
   wire FE_PHN230_n_394;
   wire FE_PHN228_n_394;
   wire FE_PHN227_n_394;
   wire FE_PHN225_n_400;
   wire FE_PHN223_n_399;
   wire FE_PHN222_n_163;
   wire FE_PHN221_n_400;
   wire FE_PHN220_n_399;
   wire FE_PHN219_n_394;
   wire FE_PHN218_In_reg_19;
   wire FE_PHN217_In_reg_20;
   wire FE_PHN216_In_reg_2;
   wire FE_PHN215_In_reg_18;
   wire FE_PHN214_In_reg_9;
   wire FE_PHN213_In_reg_14;
   wire FE_PHN212_In_reg_23;
   wire FE_PHN211_In_reg_11;
   wire FE_PHN210_In_reg_1;
   wire FE_PHN209_In_reg_15;
   wire FE_PHN208_In_reg_5;
   wire FE_PHN207_In_reg_25;
   wire FE_PHN206_In_reg_27;
   wire FE_PHN205_In_reg_8;
   wire FE_PHN204_In_reg_7;
   wire FE_PHN203_In_reg_4;
   wire FE_PHN202_In_reg_17;
   wire FE_PHN201_In_reg_10;
   wire FE_PHN200_In_reg_28;
   wire FE_PHN199_In_reg_3;
   wire FE_PHN198_n_163;
   wire FE_PHN197_n_394;
   wire FE_PHN195_n_163;
   wire FE_PHN194_counter_2;
   wire FE_PHN193_counter_0;
   wire FE_PHN192_counter_1;
   wire FE_PHN191_counter_3;
   wire FE_PHN190_In_reg_26;
   wire FE_PHN189_In_reg_12;
   wire FE_PHN188_In_reg_6;
   wire FE_PHN187_In_reg_0;
   wire FE_PHN186_In_reg_16;
   wire FE_PHN185_In_reg_24;
   wire FE_PHN184_In_reg_21;
   wire FE_PHN183_In_reg_22;
   wire FE_PHN182_n_410;
   wire FE_PHN180_n_10;
   wire FE_PHN178_n_394;
   wire FE_PHN177_n_208;
   wire FE_PHN175_counter_3;
   wire FE_PHN174_counter_0;
   wire FE_PHN173_n_407;
   wire FE_PHN170_In_reg_19;
   wire FE_PHN169_In_reg_20;
   wire FE_PHN168_In_reg_30;
   wire FE_PHN167_In_reg_2;
   wire FE_PHN166_In_reg_23;
   wire FE_PHN165_In_reg_18;
   wire FE_PHN164_In_reg_15;
   wire FE_PHN163_In_reg_9;
   wire FE_PHN162_In_reg_24;
   wire FE_PHN161_In_reg_17;
   wire FE_PHN160_In_reg_25;
   wire FE_PHN159_In_reg_4;
   wire FE_PHN158_In_reg_14;
   wire FE_PHN157_In_reg_28;
   wire FE_PHN156_In_reg_5;
   wire FE_PHN155_In_reg_1;
   wire FE_PHN154_In_reg_10;
   wire FE_PHN153_In_reg_12;
   wire FE_PHN152_In_reg_6;
   wire FE_PHN151_In_reg_11;
   wire FE_PHN150_In_reg_26;
   wire FE_PHN149_In_reg_27;
   wire FE_PHN148_In_reg_0;
   wire FE_PHN147_In_reg_7;
   wire FE_PHN146_In_reg_8;
   wire FE_PHN145_In_reg_16;
   wire FE_PHN144_In_reg_22;
   wire FE_PHN143_In_reg_21;
   wire FE_PHN142_In_reg_3;
   wire FE_PHN141_counter_3;
   wire FE_PHN140_n_0;
   wire FE_PHN139_n_405;
   wire FE_PHN138_counter_2;
   wire FE_PHN137_In_reg_13;
   wire FE_PHN136_In_reg_19;
   wire FE_PHN135_In_reg_20;
   wire FE_PHN134_In_reg_29;
   wire FE_PHN133_counter_0;
   wire FE_PHN132_In_reg_2;
   wire FE_PHN131_In_reg_23;
   wire FE_PHN130_In_reg_18;
   wire FE_PHN129_In_reg_24;
   wire FE_PHN128_In_reg_15;
   wire FE_PHN127_In_reg_17;
   wire FE_PHN126_In_reg_28;
   wire FE_PHN125_In_reg_9;
   wire FE_PHN124_In_reg_4;
   wire FE_PHN122_In_reg_25;
   wire FE_PHN121_In_reg_10;
   wire FE_PHN120_In_reg_14;
   wire FE_PHN119_In_reg_5;
   wire FE_PHN118_In_reg_12;
   wire FE_PHN117_In_reg_11;
   wire FE_PHN116_In_reg_27;
   wire FE_PHN115_In_reg_1;
   wire FE_PHN114_In_reg_0;
   wire FE_PHN113_In_reg_26;
   wire FE_PHN112_In_reg_16;
   wire FE_PHN111_In_reg_6;
   wire FE_PHN110_In_reg_7;
   wire FE_PHN109_In_reg_8;
   wire FE_PHN108_In_reg_22;
   wire FE_PHN107_In_reg_3;
   wire FE_PHN106_In_reg_21;
   wire FE_PHN105_n_410;
   wire FE_PHN103_n_163;
   wire FE_PHN102_counter_0;
   wire FE_PHN101_counter_3;
   wire FE_PHN100_counter_1;
   wire FE_PHN99_n_0;
   wire FE_PHN98_In_reg_30;
   wire FE_PHN97_counter_2;
   wire FE_PHN96_In_reg_13;
   wire FE_PHN95_In_reg_2;
   wire FE_PHN94_In_reg_18;
   wire FE_PHN93_In_reg_23;
   wire FE_PHN92_In_reg_24;
   wire FE_PHN91_In_reg_15;
   wire FE_PHN90_In_reg_17;
   wire FE_PHN89_In_reg_4;
   wire FE_PHN88_In_reg_9;
   wire FE_PHN87_In_reg_28;
   wire FE_PHN86_In_reg_25;
   wire FE_PHN85_In_reg_14;
   wire FE_PHN84_In_reg_10;
   wire FE_PHN83_In_reg_19;
   wire FE_PHN82_In_reg_11;
   wire FE_PHN81_In_reg_20;
   wire FE_PHN80_In_reg_0;
   wire FE_PHN79_In_reg_5;
   wire FE_PHN78_In_reg_16;
   wire FE_PHN77_In_reg_1;
   wire FE_PHN76_In_reg_7;
   wire FE_PHN75_In_reg_27;
   wire FE_PHN74_In_reg_22;
   wire FE_PHN73_In_reg_12;
   wire FE_PHN72_In_reg_3;
   wire FE_PHN71_In_reg_26;
   wire FE_PHN70_In_reg_6;
   wire FE_PHN69_In_reg_8;
   wire FE_PHN68_In_reg_21;
   wire FE_OFN4_DatatobeSent_7;
   wire FE_OFN3_DatatobeSent_10;
   wire FE_OFN2_DatatobeSent_24;
   wire CTS_15;
   wire CTS_14;
   wire CTS_13;
   wire CTS_12;
   wire CTS_1;
   wire FE_DBTN0_n_394;
   wire [31:0] In_reg;
   wire [4:0] counter;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire n_0;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_43;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_76;
   wire n_163;
   wire n_201;
   wire n_245;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_309;
   wire n_310;
   wire n_311;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_339;
   wire n_340;
   wire n_341;
   wire n_342;
   wire n_343;
   wire n_344;
   wire n_345;
   wire n_346;
   wire n_349;
   wire n_350;
   wire n_351;
   wire n_352;
   wire n_390;
   wire n_394;
   wire n_399;
   wire n_400;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_407;
   wire n_410;
   wire n_411;
   wire n_412;
   wire n_413;

   BUFFD4 FE_PHC346_FE_DBTN0_n_394 (.I(FE_DBTN0_n_394),
	.Z(FE_PHN346_FE_DBTN0_n_394));
   BUFFD0 FE_PHC345_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN345_n_394));
   BUFFD4 FE_PHC344_n_400 (.I(n_400),
	.Z(FE_PHN344_n_400));
   BUFFD4 FE_PHC343_In_reg_6 (.I(In_reg[6]),
	.Z(FE_PHN343_In_reg_6));
   BUFFD4 FE_PHC342_In_reg_26 (.I(In_reg[26]),
	.Z(FE_PHN342_In_reg_26));
   BUFFD4 FE_PHC341_In_reg_12 (.I(FE_PHN341_In_reg_12),
	.Z(In_reg[12]));
   BUFFD4 FE_PHC340_In_reg_0 (.I(FE_PHN340_In_reg_0),
	.Z(In_reg[0]));
   BUFFD4 FE_PHC339_In_reg_2 (.I(In_reg[2]),
	.Z(FE_PHN339_In_reg_2));
   BUFFD4 FE_PHC338_FE_DBTN0_n_394 (.I(FE_DBTN0_n_394),
	.Z(FE_PHN338_FE_DBTN0_n_394));
   CKBD4 FE_PHC337_In_reg_15 (.I(In_reg[15]),
	.Z(FE_PHN337_In_reg_15));
   CKBD1 FE_PHC336_n_394 (.I(FE_PHN336_n_394),
	.Z(FE_PHN228_n_394));
   BUFFD2 FE_PHC335_In_reg_23 (.I(FE_PHN335_In_reg_23),
	.Z(FE_PHN274_In_reg_23));
   CKBD2 FE_PHC334_n_394 (.I(FE_PHN334_n_394),
	.Z(FE_PHN197_n_394));
   CKBD1 FE_PHC333_n_394 (.I(FE_PHN333_n_394),
	.Z(FE_PHN232_n_394));
   CKBD1 FE_PHC332_In_reg_17 (.I(FE_PHN332_In_reg_17),
	.Z(FE_PHN269_In_reg_17));
   CKBD1 FE_PHC331_n_394 (.I(FE_PHN331_n_394),
	.Z(FE_PHN227_n_394));
   BUFFD6 FE_PHC330_n_394 (.I(n_394),
	.Z(FE_PHN330_n_394));
   BUFFD6 FE_PHC329_In_reg_21 (.I(In_reg[21]),
	.Z(FE_PHN329_In_reg_21));
   BUFFD16 FE_PHC328_In_reg_28 (.I(FE_PHN328_In_reg_28),
	.Z(In_reg[28]));
   CKBD2 FE_PHC327_In_reg_22 (.I(In_reg[22]),
	.Z(FE_PHN327_In_reg_22));
   CKBD2 FE_PHC326_In_reg_0 (.I(FE_PHN326_In_reg_0),
	.Z(FE_PHN340_In_reg_0));
   CKBD2 FE_PHC325_In_reg_18 (.I(FE_PHN325_In_reg_18),
	.Z(In_reg[18]));
   CKBD2 FE_PHC324_In_reg_14 (.I(In_reg[14]),
	.Z(FE_PHN324_In_reg_14));
   CKBD2 FE_PHC323_In_reg_27 (.I(FE_PHN323_In_reg_27),
	.Z(In_reg[27]));
   CKBD2 FE_PHC322_In_reg_1 (.I(In_reg[1]),
	.Z(FE_PHN322_In_reg_1));
   BUFFD3 FE_PHC321_In_reg_25 (.I(In_reg[25]),
	.Z(FE_PHN321_In_reg_25));
   CKBD2 FE_PHC320_In_reg_9 (.I(In_reg[9]),
	.Z(FE_PHN320_In_reg_9));
   BUFFD4 FE_PHC319_In_reg_16 (.I(FE_PHN319_In_reg_16),
	.Z(FE_PHN78_In_reg_16));
   BUFFD4 FE_PHC318_In_reg_26 (.I(FE_PHN318_In_reg_26),
	.Z(FE_PHN71_In_reg_26));
   BUFFD4 FE_PHC317_In_reg_12 (.I(FE_PHN317_In_reg_12),
	.Z(FE_PHN73_In_reg_12));
   BUFFD4 FE_PHC316_In_reg_8 (.I(FE_PHN316_In_reg_8),
	.Z(FE_PHN69_In_reg_8));
   BUFFD4 FE_PHC315_In_reg_24 (.I(FE_PHN315_In_reg_24),
	.Z(FE_PHN129_In_reg_24));
   BUFFD4 FE_PHC314_In_reg_6 (.I(FE_PHN314_In_reg_6),
	.Z(FE_PHN70_In_reg_6));
   BUFFD3 FE_PHC313_In_reg_3 (.I(In_reg[3]),
	.Z(FE_PHN313_In_reg_3));
   BUFFD4 FE_PHC312_n_163 (.I(FE_PHN312_n_163),
	.Z(FE_PHN222_n_163));
   BUFFD2 FE_PHC311_In_reg_7 (.I(FE_PHN311_In_reg_7),
	.Z(FE_PHN76_In_reg_7));
   BUFFD2 FE_PHC310_In_reg_5 (.I(FE_PHN310_In_reg_5),
	.Z(FE_PHN79_In_reg_5));
   BUFFD2 FE_PHC309_counter_0 (.I(FE_PHN309_counter_0),
	.Z(FE_PHN133_counter_0));
   CKBD1 FE_PHC308_n_400 (.I(FE_PHN225_n_400),
	.Z(FE_PHN308_n_400));
   CKBD1 FE_PHC307_counter_2 (.I(FE_PHN97_counter_2),
	.Z(FE_PHN307_counter_2));
   CKBD1 FE_PHC306_counter_1 (.I(FE_PHN270_counter_1),
	.Z(FE_PHN306_counter_1));
   CKBD1 FE_PHC305_n_399 (.I(n_399),
	.Z(FE_PHN305_n_399));
   CKBD0 FE_PHC304_n_394 (.I(n_394),
	.Z(FE_PHN304_n_394));
   CKBD1 FE_PHC303_n_163 (.I(n_163),
	.Z(FE_PHN303_n_163));
   CKBD16 FE_PHC302_counter_3 (.I(FE_PHN264_counter_3),
	.Z(FE_PHN302_counter_3));
   CKBD0 FE_PHC301_counter_0 (.I(counter[0]),
	.Z(FE_PHN301_counter_0));
   BUFFD4 FE_PHC300_n_407 (.I(n_407),
	.Z(FE_PHN300_n_407));
   CKBD2 FE_PHC299_In_reg_4 (.I(FE_PHN299_In_reg_4),
	.Z(In_reg[4]));
   CKBD2 FE_PHC298_In_reg_11 (.I(FE_PHN298_In_reg_11),
	.Z(In_reg[11]));
   BUFFD4 FE_PHC297_In_reg_19 (.I(FE_PHN83_In_reg_19),
	.Z(FE_PHN297_In_reg_19));
   BUFFD2 FE_PHC296_In_reg_29 (.I(FE_PHN296_In_reg_29),
	.Z(In_reg[29]));
   CKBD2 FE_PHC295_In_reg_30 (.I(In_reg[30]),
	.Z(FE_PHN295_In_reg_30));
   CKBD2 FE_PHC294_In_reg_20 (.I(FE_PHN294_In_reg_20),
	.Z(In_reg[20]));
   BUFFD4 FE_PHC293_In_reg_10 (.I(FE_PHN293_In_reg_10),
	.Z(FE_PHN121_In_reg_10));
   BUFFD4 FE_PHC292_In_reg_25 (.I(FE_PHN292_In_reg_25),
	.Z(FE_PHN207_In_reg_25));
   CKBD1 FE_PHC291_In_reg_15 (.I(FE_PHN291_In_reg_15),
	.Z(FE_PHN128_In_reg_15));
   CKBD1 FE_PHC290_In_reg_13 (.I(In_reg[13]),
	.Z(FE_PHN290_In_reg_13));
   BUFFD2 FE_PHC289_In_reg_27 (.I(FE_PHN116_In_reg_27),
	.Z(FE_PHN289_In_reg_27));
   BUFFD2 FE_PHC288_In_reg_14 (.I(FE_PHN288_In_reg_14),
	.Z(FE_PHN120_In_reg_14));
   CKBD1 FE_PHC287_In_reg_18 (.I(FE_PHN215_In_reg_18),
	.Z(FE_PHN287_In_reg_18));
   CKBD1 FE_PHC286_In_reg_28 (.I(FE_PHN286_In_reg_28),
	.Z(FE_PHN126_In_reg_28));
   BUFFD2 FE_PHC285_In_reg_9 (.I(FE_PHN285_In_reg_9),
	.Z(FE_PHN214_In_reg_9));
   CKBD1 FE_PHC284_In_reg_3 (.I(FE_PHN107_In_reg_3),
	.Z(FE_PHN284_In_reg_3));
   CKBD1 FE_PHC283_In_reg_21 (.I(FE_PHN106_In_reg_21),
	.Z(FE_PHN283_In_reg_21));
   CKBD1 FE_PHC282_In_reg_22 (.I(FE_PHN108_In_reg_22),
	.Z(FE_PHN282_In_reg_22));
   CKBD1 FE_PHC281_In_reg_0 (.I(FE_PHN281_In_reg_0),
	.Z(FE_PHN187_In_reg_0));
   CKBD1 FE_PHC280_In_reg_1 (.I(FE_PHN77_In_reg_1),
	.Z(FE_PHN280_In_reg_1));
   BUFFD2 FE_PHC279_In_reg_26 (.I(FE_PHN71_In_reg_26),
	.Z(FE_PHN279_In_reg_26));
   BUFFD2 FE_PHC278_In_reg_5 (.I(FE_PHN79_In_reg_5),
	.Z(FE_PHN278_In_reg_5));
   CKBD1 FE_PHC277_In_reg_16 (.I(FE_PHN78_In_reg_16),
	.Z(FE_PHN277_In_reg_16));
   CKBD1 FE_PHC276_In_reg_12 (.I(FE_PHN73_In_reg_12),
	.Z(FE_PHN276_In_reg_12));
   CKBD1 FE_PHC275_In_reg_8 (.I(FE_PHN69_In_reg_8),
	.Z(FE_PHN275_In_reg_8));
   BUFFD2 FE_PHC274_In_reg_23 (.I(FE_PHN274_In_reg_23),
	.Z(FE_PHN131_In_reg_23));
   CKBD1 FE_PHC273_In_reg_24 (.I(FE_PHN129_In_reg_24),
	.Z(FE_PHN273_In_reg_24));
   CKBD1 FE_PHC272_In_reg_6 (.I(FE_PHN70_In_reg_6),
	.Z(FE_PHN272_In_reg_6));
   CKBD1 FE_PHC271_In_reg_7 (.I(FE_PHN76_In_reg_7),
	.Z(FE_PHN271_In_reg_7));
   CKBD1 FE_PHC270_counter_1 (.I(FE_PHN253_counter_1),
	.Z(FE_PHN270_counter_1));
   CKBD1 FE_PHC269_In_reg_17 (.I(FE_PHN269_In_reg_17),
	.Z(In_reg[17]));
   CKBD1 FE_PHC268_n_410 (.I(FE_PHN105_n_410),
	.Z(FE_PHN268_n_410));
   BUFFD1 FE_PHC267_n_394 (.I(FE_PHN230_n_394),
	.Z(FE_PHN267_n_394));
   BUFFD0 FE_PHC266_n_399 (.I(FE_PHN266_n_399),
	.Z(FE_PHN220_n_399));
   BUFFD4 FE_PHC265_n_390 (.I(FE_PHN265_n_390),
	.Z(n_390));
   BUFFD4 FE_PHC264_counter_3 (.I(FE_PHN101_counter_3),
	.Z(FE_PHN264_counter_3));
   BUFFD4 FE_PHC263_n_405 (.I(FE_PHN263_n_405),
	.Z(FE_PHN139_n_405));
   CKBD16 FE_PHC262_n_0 (.I(FE_PHN262_n_0),
	.Z(n_0));
   CKBD0 FE_PHC261_counter_2 (.I(counter[2]),
	.Z(FE_PHN261_counter_2));
   BUFFD4 FE_PHC260_In_reg_2 (.I(FE_PHN260_In_reg_2),
	.Z(FE_PHN132_In_reg_2));
   CKBD1 FE_PHC259_In_reg_4 (.I(FE_PHN259_In_reg_4),
	.Z(FE_PHN124_In_reg_4));
   BUFFD2 FE_PHC258_In_reg_20 (.I(FE_PHN81_In_reg_20),
	.Z(FE_PHN258_In_reg_20));
   CKBD1 FE_PHC257_In_reg_11 (.I(FE_PHN211_In_reg_11),
	.Z(FE_PHN257_In_reg_11));
   BUFFD6 FE_PHC256_In_reg_10 (.I(FE_PHN121_In_reg_10),
	.Z(FE_PHN256_In_reg_10));
   BUFFD4 FE_PHC255_In_reg_19 (.I(FE_PHN255_In_reg_19),
	.Z(FE_PHN218_In_reg_19));
   CKBD2 FE_PHC254_n_399 (.I(n_399),
	.Z(FE_PHN254_n_399));
   BUFFD6 FE_PHC253_counter_1 (.I(FE_PHN192_counter_1),
	.Z(FE_PHN253_counter_1));
   BUFFD1 FE_PHC252_n_163 (.I(FE_PHN222_n_163),
	.Z(FE_PHN252_n_163));
   BUFFD1 FE_PSC250_counter_3 (.I(FE_PHN302_counter_3),
	.Z(FE_PSN250_counter_3));
   BUFFD2 FE_PHC249_n_407 (.I(FE_PHN247_n_407),
	.Z(FE_PHN249_n_407));
   BUFFD0 FE_PHC248_n_394 (.I(FE_PHN330_n_394),
	.Z(FE_PHN248_n_394));
   CKBD1 FE_PHC247_n_407 (.I(FE_PHN173_n_407),
	.Z(FE_PHN247_n_407));
   INVD8 FE_PHC245_In_reg_29 (.I(FE_PHN245_In_reg_29),
	.ZN(FE_PHN134_In_reg_29));
   BUFFD4 FE_PHC244_n_407 (.I(FE_PHN173_n_407),
	.Z(FE_PHN244_n_407));
   BUFFD4 FE_PHC243_n_201 (.I(n_201),
	.Z(FE_PHN243_n_201));
   CKBD8 FE_PHC242_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN242_n_394));
   CKBD1 FE_PHC241_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN241_n_394));
   CKBD1 FE_PHC240_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN240_n_394));
   BUFFD4 FE_PHC239_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN239_n_394));
   CKBD1 FE_PHC238_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN238_n_394));
   CKBD1 FE_PHC237_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN237_n_394));
   CKBD4 FE_PHC236_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN236_n_394));
   CKBD4 FE_PHC235_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN235_n_394));
   CKBD4 FE_PHC234_n_394 (.I(FE_PHN178_n_394),
	.Z(FE_PHN234_n_394));
   CKBD12 FE_PHC230_n_394 (.I(n_394),
	.Z(FE_PHN230_n_394));
   CKBD0 FE_PHC229_n_394 (.I(n_394),
	.Z(FE_PHN333_n_394));
   CKBD0 FE_PHC228_n_394 (.I(n_394),
	.Z(FE_PHN336_n_394));
   CKBD0 FE_PHC227_n_394 (.I(n_394),
	.Z(FE_PHN331_n_394));
   BUFFD2 FE_PHC225_n_400 (.I(n_400),
	.Z(FE_PHN225_n_400));
   BUFFD0 FE_PHC223_n_399 (.I(FE_PHN305_n_399),
	.Z(FE_PHN223_n_399));
   CKND8 FE_PHC222_n_163 (.I(FE_PHN103_n_163),
	.ZN(FE_PHN312_n_163));
   BUFFD2 FE_PHC221_n_400 (.I(FE_PHN344_n_400),
	.Z(FE_PHN221_n_400));
   CKBD8 FE_PHC220_n_399 (.I(FE_PHN254_n_399),
	.Z(FE_PHN266_n_399));
   CKBD1 FE_PHC219_n_394 (.I(FE_PHN304_n_394),
	.Z(FE_PHN219_n_394));
   CKND8 FE_PHC218_In_reg_19 (.I(FE_PHN170_In_reg_19),
	.ZN(FE_PHN255_In_reg_19));
   CKND8 FE_PHC217_In_reg_20 (.I(FE_PHN169_In_reg_20),
	.ZN(FE_PHN217_In_reg_20));
   CKND8 FE_PHC216_In_reg_2 (.I(FE_PHN167_In_reg_2),
	.ZN(FE_PHN216_In_reg_2));
   CKND8 FE_PHC215_In_reg_18 (.I(FE_PHN165_In_reg_18),
	.ZN(FE_PHN215_In_reg_18));
   INVD8 FE_PHC214_In_reg_9 (.I(FE_PHN163_In_reg_9),
	.ZN(FE_PHN285_In_reg_9));
   CKND8 FE_PHC213_In_reg_14 (.I(FE_PHN324_In_reg_14),
	.ZN(FE_PHN213_In_reg_14));
   CKND8 FE_PHC212_In_reg_23 (.I(FE_PHN166_In_reg_23),
	.ZN(FE_PHN212_In_reg_23));
   CKND8 FE_PHC211_In_reg_11 (.I(FE_PHN151_In_reg_11),
	.ZN(FE_PHN211_In_reg_11));
   CKND8 FE_PHC210_In_reg_1 (.I(FE_PHN155_In_reg_1),
	.ZN(FE_PHN210_In_reg_1));
   INVD8 FE_PHC209_In_reg_15 (.I(FE_PHN164_In_reg_15),
	.ZN(FE_PHN209_In_reg_15));
   CKND8 FE_PHC208_In_reg_5 (.I(FE_PHN156_In_reg_5),
	.ZN(FE_PHN208_In_reg_5));
   CKND8 FE_PHC207_In_reg_25 (.I(FE_PHN160_In_reg_25),
	.ZN(FE_PHN292_In_reg_25));
   CKND8 FE_PHC206_In_reg_27 (.I(FE_PHN149_In_reg_27),
	.ZN(FE_PHN206_In_reg_27));
   CKND8 FE_PHC205_In_reg_8 (.I(FE_PHN146_In_reg_8),
	.ZN(FE_PHN205_In_reg_8));
   INVD8 FE_PHC204_In_reg_7 (.I(FE_PHN147_In_reg_7),
	.ZN(FE_PHN204_In_reg_7));
   CKND8 FE_PHC203_In_reg_4 (.I(FE_PHN159_In_reg_4),
	.ZN(FE_PHN203_In_reg_4));
   CKND8 FE_PHC202_In_reg_17 (.I(FE_PHN161_In_reg_17),
	.ZN(FE_PHN202_In_reg_17));
   INVD8 FE_PHC201_In_reg_10 (.I(FE_PHN154_In_reg_10),
	.ZN(FE_PHN201_In_reg_10));
   INVD8 FE_PHC200_In_reg_28 (.I(FE_PHN157_In_reg_28),
	.ZN(FE_PHN200_In_reg_28));
   CKND8 FE_PHC199_In_reg_3 (.I(FE_PHN142_In_reg_3),
	.ZN(FE_PHN199_In_reg_3));
   CKND8 FE_PHC198_n_163 (.I(FE_PHN303_n_163),
	.ZN(FE_PHN198_n_163));
   CKBD1 FE_PHC197_n_394 (.I(n_394),
	.Z(FE_PHN334_n_394));
   CKND8 FE_PHC195_n_163 (.I(FE_PHN198_n_163),
	.ZN(FE_PHN195_n_163));
   BUFFD2 FE_PHC194_counter_2 (.I(FE_PHN261_counter_2),
	.Z(FE_PHN194_counter_2));
   BUFFD3 FE_PHC193_counter_0 (.I(FE_PHN301_counter_0),
	.Z(FE_PHN193_counter_0));
   CKBD0 FE_PHC192_counter_1 (.I(counter[1]),
	.Z(FE_PHN192_counter_1));
   BUFFD4 FE_PHC191_counter_3 (.I(FE_PHN264_counter_3),
	.Z(FE_PHN191_counter_3));
   CKND8 FE_PHC190_In_reg_26 (.I(FE_PHN150_In_reg_26),
	.ZN(FE_PHN190_In_reg_26));
   CKND8 FE_PHC189_In_reg_12 (.I(FE_PHN153_In_reg_12),
	.ZN(FE_PHN189_In_reg_12));
   INVD8 FE_PHC188_In_reg_6 (.I(FE_PHN152_In_reg_6),
	.ZN(FE_PHN188_In_reg_6));
   CKND8 FE_PHC187_In_reg_0 (.I(FE_PHN148_In_reg_0),
	.ZN(FE_PHN281_In_reg_0));
   INVD8 FE_PHC186_In_reg_16 (.I(FE_PHN145_In_reg_16),
	.ZN(FE_PHN186_In_reg_16));
   INVD8 FE_PHC185_In_reg_24 (.I(In_reg[24]),
	.ZN(FE_PHN185_In_reg_24));
   CKND8 FE_PHC184_In_reg_21 (.I(FE_PHN143_In_reg_21),
	.ZN(FE_PHN184_In_reg_21));
   INVD8 FE_PHC183_In_reg_22 (.I(FE_PHN144_In_reg_22),
	.ZN(FE_PHN183_In_reg_22));
   CKND8 FE_PHC182_n_410 (.I(n_410),
	.ZN(FE_PHN182_n_410));
   BUFFD0 FE_PHC180_n_10 (.I(n_10),
	.Z(FE_PHN180_n_10));
   BUFFD16 FE_PHC178_n_394 (.I(n_394),
	.Z(FE_PHN178_n_394));
   CKBD16 FE_PHC175_counter_3 (.I(FE_PHN264_counter_3),
	.Z(FE_PHN175_counter_3));
   CKND8 FE_PHC174_counter_0 (.I(FE_PHN193_counter_0),
	.ZN(FE_PHN174_counter_0));
   BUFFD4 FE_PHC173_n_407 (.I(FE_PHN300_n_407),
	.Z(FE_PHN173_n_407));
   CKND8 FE_PHC170_In_reg_19 (.I(FE_PHN136_In_reg_19),
	.ZN(FE_PHN170_In_reg_19));
   CKND8 FE_PHC169_In_reg_20 (.I(FE_PHN135_In_reg_20),
	.ZN(FE_PHN169_In_reg_20));
   INVD8 FE_PHC168_In_reg_30 (.I(FE_PHN98_In_reg_30),
	.ZN(FE_PHN168_In_reg_30));
   CKND8 FE_PHC167_In_reg_2 (.I(FE_PHN95_In_reg_2),
	.ZN(FE_PHN167_In_reg_2));
   CKND8 FE_PHC166_In_reg_23 (.I(FE_PHN93_In_reg_23),
	.ZN(FE_PHN166_In_reg_23));
   CKND8 FE_PHC165_In_reg_18 (.I(FE_PHN130_In_reg_18),
	.ZN(FE_PHN165_In_reg_18));
   INVD8 FE_PHC164_In_reg_15 (.I(FE_PHN91_In_reg_15),
	.ZN(FE_PHN164_In_reg_15));
   INVD8 FE_PHC163_In_reg_9 (.I(FE_PHN125_In_reg_9),
	.ZN(FE_PHN163_In_reg_9));
   INVD8 FE_PHC162_In_reg_24 (.I(FE_PHN185_In_reg_24),
	.ZN(FE_PHN162_In_reg_24));
   CKND8 FE_PHC161_In_reg_17 (.I(FE_PHN90_In_reg_17),
	.ZN(FE_PHN161_In_reg_17));
   CKND8 FE_PHC160_In_reg_25 (.I(FE_PHN122_In_reg_25),
	.ZN(FE_PHN160_In_reg_25));
   CKND8 FE_PHC159_In_reg_4 (.I(FE_PHN89_In_reg_4),
	.ZN(FE_PHN159_In_reg_4));
   CKND8 FE_PHC158_In_reg_14 (.I(FE_PHN213_In_reg_14),
	.ZN(FE_PHN158_In_reg_14));
   INVD8 FE_PHC157_In_reg_28 (.I(In_reg[28]),
	.ZN(FE_PHN157_In_reg_28));
   CKND8 FE_PHC156_In_reg_5 (.I(FE_PHN119_In_reg_5),
	.ZN(FE_PHN156_In_reg_5));
   CKND8 FE_PHC155_In_reg_1 (.I(FE_PHN115_In_reg_1),
	.ZN(FE_PHN155_In_reg_1));
   INVD8 FE_PHC154_In_reg_10 (.I(FE_PHN84_In_reg_10),
	.ZN(FE_PHN154_In_reg_10));
   CKND8 FE_PHC153_In_reg_12 (.I(In_reg[12]),
	.ZN(FE_PHN153_In_reg_12));
   INVD8 FE_PHC152_In_reg_6 (.I(FE_PHN111_In_reg_6),
	.ZN(FE_PHN152_In_reg_6));
   CKND8 FE_PHC151_In_reg_11 (.I(FE_PHN117_In_reg_11),
	.ZN(FE_PHN151_In_reg_11));
   CKND8 FE_PHC150_In_reg_26 (.I(FE_PHN113_In_reg_26),
	.ZN(FE_PHN150_In_reg_26));
   CKND8 FE_PHC149_In_reg_27 (.I(FE_PHN75_In_reg_27),
	.ZN(FE_PHN149_In_reg_27));
   CKND8 FE_PHC148_In_reg_0 (.I(FE_PHN114_In_reg_0),
	.ZN(FE_PHN148_In_reg_0));
   INVD8 FE_PHC147_In_reg_7 (.I(FE_PHN110_In_reg_7),
	.ZN(FE_PHN147_In_reg_7));
   CKND8 FE_PHC146_In_reg_8 (.I(FE_PHN109_In_reg_8),
	.ZN(FE_PHN146_In_reg_8));
   INVD8 FE_PHC145_In_reg_16 (.I(FE_PHN112_In_reg_16),
	.ZN(FE_PHN145_In_reg_16));
   INVD8 FE_PHC144_In_reg_22 (.I(FE_PHN74_In_reg_22),
	.ZN(FE_PHN144_In_reg_22));
   CKND8 FE_PHC143_In_reg_21 (.I(FE_PHN68_In_reg_21),
	.ZN(FE_PHN143_In_reg_21));
   CKND8 FE_PHC142_In_reg_3 (.I(FE_PHN72_In_reg_3),
	.ZN(FE_PHN142_In_reg_3));
   CKBD16 FE_PHC141_counter_3 (.I(FE_PHN175_counter_3),
	.Z(FE_PHN141_counter_3));
   CKND8 FE_PHC140_n_0 (.I(FE_PHN99_n_0),
	.ZN(FE_PHN140_n_0));
   BUFFD4 FE_PHC139_n_405 (.I(n_405),
	.Z(FE_PHN263_n_405));
   INVD8 FE_PHC138_counter_2 (.I(FE_PHN194_counter_2),
	.ZN(FE_PHN138_counter_2));
   BUFFD3 FE_PHC137_In_reg_13 (.I(FE_PHN96_In_reg_13),
	.Z(FE_PHN137_In_reg_13));
   CKND8 FE_PHC136_In_reg_19 (.I(In_reg[19]),
	.ZN(FE_PHN136_In_reg_19));
   CKND8 FE_PHC135_In_reg_20 (.I(In_reg[20]),
	.ZN(FE_PHN135_In_reg_20));
   INVD2 FE_PHC134_In_reg_29 (.I(In_reg[29]),
	.ZN(FE_PHN245_In_reg_29));
   CKND8 FE_PHC133_counter_0 (.I(FE_PHN174_counter_0),
	.ZN(FE_PHN309_counter_0));
   CKND8 FE_PHC132_In_reg_2 (.I(FE_PHN216_In_reg_2),
	.ZN(FE_PHN260_In_reg_2));
   CKND8 FE_PHC131_In_reg_23 (.I(FE_PHN212_In_reg_23),
	.ZN(FE_PHN335_In_reg_23));
   CKND8 FE_PHC130_In_reg_18 (.I(FE_PHN94_In_reg_18),
	.ZN(FE_PHN130_In_reg_18));
   INVD8 FE_PHC129_In_reg_24 (.I(FE_PHN92_In_reg_24),
	.ZN(FE_PHN315_In_reg_24));
   INVD8 FE_PHC128_In_reg_15 (.I(FE_PHN209_In_reg_15),
	.ZN(FE_PHN291_In_reg_15));
   CKND8 FE_PHC127_In_reg_17 (.I(FE_PHN202_In_reg_17),
	.ZN(FE_PHN127_In_reg_17));
   INVD8 FE_PHC126_In_reg_28 (.I(FE_PHN87_In_reg_28),
	.ZN(FE_PHN286_In_reg_28));
   INVD8 FE_PHC125_In_reg_9 (.I(FE_PHN88_In_reg_9),
	.ZN(FE_PHN125_In_reg_9));
   CKND8 FE_PHC124_In_reg_4 (.I(FE_PHN203_In_reg_4),
	.ZN(FE_PHN259_In_reg_4));
   CKND8 FE_PHC122_In_reg_25 (.I(FE_PHN86_In_reg_25),
	.ZN(FE_PHN122_In_reg_25));
   INVD8 FE_PHC121_In_reg_10 (.I(FE_PHN201_In_reg_10),
	.ZN(FE_PHN293_In_reg_10));
   CKND8 FE_PHC120_In_reg_14 (.I(FE_PHN85_In_reg_14),
	.ZN(FE_PHN288_In_reg_14));
   CKND8 FE_PHC119_In_reg_5 (.I(In_reg[5]),
	.ZN(FE_PHN119_In_reg_5));
   CKND8 FE_PHC118_In_reg_12 (.I(FE_PHN189_In_reg_12),
	.ZN(FE_PHN118_In_reg_12));
   CKND8 FE_PHC117_In_reg_11 (.I(FE_PHN82_In_reg_11),
	.ZN(FE_PHN117_In_reg_11));
   CKND8 FE_PHC116_In_reg_27 (.I(FE_PHN206_In_reg_27),
	.ZN(FE_PHN116_In_reg_27));
   CKND8 FE_PHC115_In_reg_1 (.I(FE_PHN322_In_reg_1),
	.ZN(FE_PHN115_In_reg_1));
   CKND8 FE_PHC114_In_reg_0 (.I(FE_PHN80_In_reg_0),
	.ZN(FE_PHN114_In_reg_0));
   CKND8 FE_PHC113_In_reg_26 (.I(FE_PHN342_In_reg_26),
	.ZN(FE_PHN113_In_reg_26));
   INVD8 FE_PHC112_In_reg_16 (.I(In_reg[16]),
	.ZN(FE_PHN112_In_reg_16));
   INVD8 FE_PHC111_In_reg_6 (.I(FE_PHN343_In_reg_6),
	.ZN(FE_PHN111_In_reg_6));
   INVD8 FE_PHC110_In_reg_7 (.I(In_reg[7]),
	.ZN(FE_PHN110_In_reg_7));
   CKND8 FE_PHC109_In_reg_8 (.I(In_reg[8]),
	.ZN(FE_PHN109_In_reg_8));
   INVD8 FE_PHC108_In_reg_22 (.I(FE_PHN183_In_reg_22),
	.ZN(FE_PHN108_In_reg_22));
   CKND8 FE_PHC107_In_reg_3 (.I(FE_PHN199_In_reg_3),
	.ZN(FE_PHN107_In_reg_3));
   CKND8 FE_PHC106_In_reg_21 (.I(FE_PHN184_In_reg_21),
	.ZN(FE_PHN106_In_reg_21));
   CKND8 FE_PHC105_n_410 (.I(FE_PHN182_n_410),
	.ZN(FE_PHN105_n_410));
   CKND8 FE_PHC103_n_163 (.I(FE_PHN195_n_163),
	.ZN(FE_PHN103_n_163));
   BUFFD2 FE_PHC102_counter_0 (.I(counter[0]),
	.Z(FE_PHN102_counter_0));
   BUFFD1 FE_PHC100_counter_1 (.I(counter[1]),
	.Z(FE_PHN100_counter_1));
   CKND8 FE_PHC99_n_0 (.I(n_0),
	.ZN(FE_PHN99_n_0));
   INVD8 FE_PHC98_In_reg_30 (.I(FE_PHN295_In_reg_30),
	.ZN(FE_PHN98_In_reg_30));
   INVD8 FE_PHC97_counter_2 (.I(FE_PHN138_counter_2),
	.ZN(FE_PHN97_counter_2));
   CKBD0 FE_PHC96_In_reg_13 (.I(FE_PHN290_In_reg_13),
	.Z(FE_PHN96_In_reg_13));
   CKND8 FE_PHC95_In_reg_2 (.I(FE_PHN339_In_reg_2),
	.ZN(FE_PHN95_In_reg_2));
   CKND8 FE_PHC94_In_reg_18 (.I(In_reg[18]),
	.ZN(FE_PHN94_In_reg_18));
   INVD2 FE_PHC93_In_reg_23 (.I(In_reg[23]),
	.ZN(FE_PHN93_In_reg_23));
   INVD8 FE_PHC92_In_reg_24 (.I(FE_PHN162_In_reg_24),
	.ZN(FE_PHN92_In_reg_24));
   INVD8 FE_PHC91_In_reg_15 (.I(FE_PHN337_In_reg_15),
	.ZN(FE_PHN91_In_reg_15));
   INVD2 FE_PHC90_In_reg_17 (.I(In_reg[17]),
	.ZN(FE_PHN90_In_reg_17));
   CKND8 FE_PHC89_In_reg_4 (.I(In_reg[4]),
	.ZN(FE_PHN89_In_reg_4));
   INVD8 FE_PHC88_In_reg_9 (.I(FE_PHN320_In_reg_9),
	.ZN(FE_PHN88_In_reg_9));
   INVD8 FE_PHC87_In_reg_28 (.I(FE_PHN200_In_reg_28),
	.ZN(FE_PHN87_In_reg_28));
   CKND8 FE_PHC86_In_reg_25 (.I(FE_PHN321_In_reg_25),
	.ZN(FE_PHN86_In_reg_25));
   CKND8 FE_PHC85_In_reg_14 (.I(FE_PHN158_In_reg_14),
	.ZN(FE_PHN85_In_reg_14));
   INVD8 FE_PHC84_In_reg_10 (.I(In_reg[10]),
	.ZN(FE_PHN84_In_reg_10));
   CKND8 FE_PHC83_In_reg_19 (.I(FE_PHN218_In_reg_19),
	.ZN(FE_PHN83_In_reg_19));
   CKND8 FE_PHC82_In_reg_11 (.I(In_reg[11]),
	.ZN(FE_PHN82_In_reg_11));
   CKND8 FE_PHC81_In_reg_20 (.I(FE_PHN217_In_reg_20),
	.ZN(FE_PHN81_In_reg_20));
   CKND8 FE_PHC80_In_reg_0 (.I(In_reg[0]),
	.ZN(FE_PHN80_In_reg_0));
   CKND8 FE_PHC79_In_reg_5 (.I(FE_PHN208_In_reg_5),
	.ZN(FE_PHN310_In_reg_5));
   INVD8 FE_PHC78_In_reg_16 (.I(FE_PHN186_In_reg_16),
	.ZN(FE_PHN319_In_reg_16));
   CKND8 FE_PHC77_In_reg_1 (.I(FE_PHN210_In_reg_1),
	.ZN(FE_PHN77_In_reg_1));
   INVD8 FE_PHC76_In_reg_7 (.I(FE_PHN204_In_reg_7),
	.ZN(FE_PHN311_In_reg_7));
   CKND8 FE_PHC75_In_reg_27 (.I(In_reg[27]),
	.ZN(FE_PHN75_In_reg_27));
   INVD8 FE_PHC74_In_reg_22 (.I(FE_PHN327_In_reg_22),
	.ZN(FE_PHN74_In_reg_22));
   CKND8 FE_PHC73_In_reg_12 (.I(FE_PHN118_In_reg_12),
	.ZN(FE_PHN317_In_reg_12));
   CKND8 FE_PHC72_In_reg_3 (.I(FE_PHN313_In_reg_3),
	.ZN(FE_PHN72_In_reg_3));
   CKND8 FE_PHC71_In_reg_26 (.I(FE_PHN190_In_reg_26),
	.ZN(FE_PHN318_In_reg_26));
   INVD8 FE_PHC70_In_reg_6 (.I(FE_PHN188_In_reg_6),
	.ZN(FE_PHN314_In_reg_6));
   CKND8 FE_PHC69_In_reg_8 (.I(FE_PHN205_In_reg_8),
	.ZN(FE_PHN316_In_reg_8));
   CKND8 FE_PHC68_In_reg_21 (.I(FE_PHN329_In_reg_21),
	.ZN(FE_PHN68_In_reg_21));
   CKBD3 FE_OFC4_DatatobeSent_7 (.I(DataIn[7]),
	.Z(FE_OFN4_DatatobeSent_7));
   CKBD3 FE_OFC3_DatatobeSent_10 (.I(DataIn[10]),
	.Z(FE_OFN3_DatatobeSent_10));
   CKBD3 FE_OFC2_DatatobeSent_24 (.I(DataIn[24]),
	.Z(FE_OFN2_DatatobeSent_24));
   CKBD3 CTS_ccd_BUF_clk_bit_G0_L1_2 (.I(CLKBit),
	.Z(CTS_15));
   CKBD8 CTS_cdb_BUF_clk_bit_G0_L2_1 (.I(CTS_14),
	.Z(CTS_13));
   CKBD3 CTS_ccd_BUF_clk_bit_G0_L1_1 (.I(CLKBit),
	.Z(CTS_14));
   CKBD3 CTS_ccd_BUF_clk_word_G0_L1_2 (.I(CTS_1),
	.Z(CTS_12));
   CKBD16 CTS_ccl_BUF_clk_word_G0_L1_1 (.I(CTS_1),
	.Z(CLKWord));
   CKND12 FE_DBTC0_n_394 (.I(n_394),
	.ZN(FE_DBTN0_n_394));
   DFCNQD1 \In_reg_reg[0]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_43),
	.Q(FE_PHN326_In_reg_0));
   DFCNQD1 \In_reg_reg[1]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_45),
	.Q(In_reg[1]));
   DFCNQD1 \In_reg_reg[2]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_46),
	.Q(In_reg[2]));
   DFCNQD1 \In_reg_reg[3]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_47),
	.Q(In_reg[3]));
   DFCNQD1 \In_reg_reg[4]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_48),
	.Q(FE_PHN299_In_reg_4));
   DFCNQD1 \In_reg_reg[5]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_49),
	.Q(In_reg[5]));
   DFCNQD1 \In_reg_reg[6]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_50),
	.Q(In_reg[6]));
   DFCNQD1 \In_reg_reg[7]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_51),
	.Q(In_reg[7]));
   DFCNQD1 \In_reg_reg[8]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_52),
	.Q(In_reg[8]));
   DFCNQD1 \In_reg_reg[9]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_53),
	.Q(In_reg[9]));
   DFCNQD1 \In_reg_reg[10]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_54),
	.Q(In_reg[10]));
   DFCNQD1 \In_reg_reg[11]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_55),
	.Q(FE_PHN298_In_reg_11));
   DFCNQD1 \In_reg_reg[12]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_56),
	.Q(FE_PHN341_In_reg_12));
   DFCNQD1 \In_reg_reg[13]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_57),
	.Q(In_reg[13]));
   DFCNQD1 \In_reg_reg[14]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_58),
	.Q(In_reg[14]));
   DFCNQD1 \In_reg_reg[15]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_59),
	.Q(In_reg[15]));
   DFCNQD1 \In_reg_reg[16]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_60),
	.Q(In_reg[16]));
   DFCNQD1 \In_reg_reg[17]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_61),
	.Q(FE_PHN332_In_reg_17));
   DFCNQD1 \In_reg_reg[18]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_62),
	.Q(FE_PHN325_In_reg_18));
   DFCNQD1 \In_reg_reg[19]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_63),
	.Q(In_reg[19]));
   DFCNQD1 \In_reg_reg[20]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_412),
	.Q(FE_PHN294_In_reg_20));
   DFCNQD1 \In_reg_reg[21]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_411),
	.Q(In_reg[21]));
   DFCNQD1 \In_reg_reg[22]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_66),
	.Q(In_reg[22]));
   DFCNQD1 \In_reg_reg[23]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_67),
	.Q(In_reg[23]));
   DFCNQD1 \In_reg_reg[24]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_68),
	.Q(In_reg[24]));
   DFCNQD1 \In_reg_reg[25]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_69),
	.Q(In_reg[25]));
   DFCNQD1 \In_reg_reg[26]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_70),
	.Q(In_reg[26]));
   DFCNQD1 \In_reg_reg[27]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_71),
	.Q(FE_PHN323_In_reg_27));
   DFCNQD1 \In_reg_reg[28]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_72),
	.Q(FE_PHN328_In_reg_28));
   DFCNQD1 \In_reg_reg[29]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(n_73),
	.Q(FE_PHN296_In_reg_29));
   DFCND1 \In_reg_reg[30]  (.CDN(RSTn),
	.CP(CTS_13),
	.D(FE_PHN268_n_410),
	.Q(UNCONNECTED),
	.QN(In_reg[30]));
   DFCND1 \In_reg_reg[31]  (.CDN(FE_OFN0_rst_int),
	.CP(CTS_13),
	.D(n_311),
	.Q(UNCONNECTED0),
	.QN(n_76));
   IOA21D1 g949__9682 (.A1(FE_PHN197_n_394),
	.A2(FE_PHN126_In_reg_28),
	.B(n_346),
	.ZN(n_73));
   IOA21D1 g951__2683 (.A1(FE_PHN197_n_394),
	.A2(FE_PHN289_In_reg_27),
	.B(n_342),
	.ZN(n_72));
   IOA21D2 g953__1309 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN279_In_reg_26),
	.B(n_255),
	.ZN(n_71));
   IOA21D1 g955__6877 (.A1(FE_PHN197_n_394),
	.A2(FE_PHN207_In_reg_25),
	.B(n_335),
	.ZN(n_70));
   IOA21D2 g957__2900 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN273_In_reg_24),
	.B(n_258),
	.ZN(n_69));
   IOA21D2 g959__2391 (.A1(FE_PHN227_n_394),
	.A2(FE_PHN131_In_reg_23),
	.B(n_336),
	.ZN(n_68));
   IOA21D2 g961__7675 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN282_In_reg_22),
	.B(n_253),
	.ZN(n_67));
   IOA21D2 g963__7118 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN283_In_reg_21),
	.B(n_259),
	.ZN(n_66));
   IOA21D2 g969__5953 (.A1(FE_PHN232_n_394),
	.A2(FE_PHN287_In_reg_18),
	.B(n_309),
	.ZN(n_63));
   IOA21D2 g971__5703 (.A1(FE_PHN248_n_394),
	.A2(FE_PHN127_In_reg_17),
	.B(n_245),
	.ZN(n_62));
   IOA21D2 g973__7114 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN277_In_reg_16),
	.B(n_254),
	.ZN(n_61));
   IOA21D1 g975__5266 (.A1(FE_PHN228_n_394),
	.A2(FE_PHN128_In_reg_15),
	.B(n_350),
	.ZN(n_60));
   IOA21D1 g977__2250 (.A1(FE_PHN267_n_394),
	.A2(FE_PHN120_In_reg_14),
	.B(n_345),
	.ZN(n_59));
   IOA21D2 g979__6083 (.A1(FE_PHN345_n_394),
	.A2(FE_PHN137_In_reg_13),
	.B(n_352),
	.ZN(n_58));
   IOA21D2 g981__2703 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN276_In_reg_12),
	.B(n_257),
	.ZN(n_57));
   IOA21D1 g983__5795 (.A1(FE_PHN237_n_394),
	.A2(FE_PHN257_In_reg_11),
	.B(n_310),
	.ZN(n_56));
   IOA21D2 g985__7344 (.A1(FE_PHN237_n_394),
	.A2(FE_PHN256_In_reg_10),
	.B(n_351),
	.ZN(n_55));
   IOA21D2 g987__1840 (.A1(FE_PHN242_n_394),
	.A2(FE_PHN214_In_reg_9),
	.B(n_341),
	.ZN(n_54));
   IOA21D2 g989__5019 (.A1(FE_PHN238_n_394),
	.A2(FE_PHN275_In_reg_8),
	.B(n_260),
	.ZN(n_53));
   IOA21D2 g991__1857 (.A1(FE_PHN219_n_394),
	.A2(FE_PHN271_In_reg_7),
	.B(n_339),
	.ZN(n_52));
   IOA21D2 g993__9906 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN272_In_reg_6),
	.B(n_256),
	.ZN(n_51));
   IOA21D2 g995__8780 (.A1(FE_PHN219_n_394),
	.A2(FE_PHN278_In_reg_5),
	.B(n_337),
	.ZN(n_50));
   IOA21D1 g997__4296 (.A1(FE_PHN240_n_394),
	.A2(FE_PHN124_In_reg_4),
	.B(n_343),
	.ZN(n_49));
   IOA21D2 g999__3772 (.A1(FE_PHN239_n_394),
	.A2(FE_PHN284_In_reg_3),
	.B(n_338),
	.ZN(n_48));
   IOA21D1 g1001__1474 (.A1(FE_PHN241_n_394),
	.A2(FE_PHN132_In_reg_2),
	.B(n_349),
	.ZN(n_47));
   IOA21D2 g1003__4547 (.A1(FE_PHN234_n_394),
	.A2(FE_PHN280_In_reg_1),
	.B(n_340),
	.ZN(n_46));
   IOA21D2 g1005__9682 (.A1(FE_PHN177_n_208),
	.A2(FE_PHN187_In_reg_0),
	.B(n_344),
	.ZN(n_45));
   INR2XD1 g1008__1309 (.A1(DataIn[0]),
	.B1(FE_PHN235_n_394),
	.ZN(n_43));
   DFSNQD4 \counter_reg[4]  (.CP(CLKBit),
	.D(n_13),
	.Q(CTS_1),
	.SDN(RSTn));
   OAI21D2 g400__6877 (.A1(n_10),
	.A2(FE_PHN140_n_0),
	.B(n_12),
	.ZN(n_13));
   DFSNQD4 \counter_reg[3]  (.CP(CTS_15),
	.D(n_11),
	.Q(FE_PHN101_counter_3),
	.SDN(RSTn));
   ND2D2 g402__2900 (.A1(n_10),
	.A2(FE_PHN140_n_0),
	.ZN(n_12));
   IND2D1 g403__2391 (.A1(n_9),
	.B1(FE_PHN180_n_10),
	.ZN(n_11));
   DFSNQD4 \counter_reg[2]  (.CP(CTS_15),
	.D(n_8),
	.Q(counter[2]),
	.SDN(FE_OFN0_rst_int));
   INR2D2 g405__7675 (.A1(FE_PHN141_counter_3),
	.B1(FE_PHN221_n_400),
	.ZN(n_9));
   CKND2D4 g406__7118 (.A1(n_400),
	.A2(FE_PHN243_n_201),
	.ZN(n_10));
   AO21D2 g407__8757 (.A1(FE_PHN223_n_399),
	.A2(FE_PHN307_counter_2),
	.B(FE_PHN308_n_400),
	.Z(n_8));
   DFSNQD4 \counter_reg[1]  (.CP(CTS_15),
	.D(n_6),
	.Q(counter[1]),
	.SDN(FE_OFN0_rst_int));
   IOA21D2 g410__5953 (.A1(FE_PHN306_counter_1),
	.A2(FE_PHN133_counter_0),
	.B(FE_PHN220_n_399),
	.ZN(n_6));
   DFSNQD4 \counter_reg[0]  (.CP(CTS_15),
	.D(FE_PHN252_n_163),
	.Q(counter[0]),
	.SDN(FE_OFN0_rst_int));
   CKBD1 fopt (.I(CTS_12),
	.Z(FE_PHN262_n_0));
   INVD2 fopt1070 (.I(FE_PHN264_counter_3),
	.ZN(n_201));
   INVD4 fopt1075 (.I(n_413),
	.ZN(FE_PHN177_n_208));
   CKND2D2 g1030__1112 (.A1(FE_PHN338_FE_DBTN0_n_394),
	.A2(DataIn[18]),
	.ZN(n_245));
   ND2D2 g1014__1121 (.A1(DataIn[23]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_253));
   ND2D2 g1022__1122 (.A1(DataIn[17]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_254));
   ND2D2 g1007__1123 (.A1(DataIn[27]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_255));
   ND2D2 g1010__1124 (.A1(FE_OFN4_DatatobeSent_7),
	.A2(FE_DBTN0_n_394),
	.ZN(n_256));
   ND2D2 g1023__1125 (.A1(DataIn[13]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_257));
   ND2D2 g1012__1126 (.A1(DataIn[25]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_258));
   ND2D2 g1036__1127 (.A1(DataIn[22]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_259));
   CKND2D2 g1016__1128 (.A1(DataIn[9]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_260));
   ND2D2 g1031__1178 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[19]),
	.ZN(n_309));
   CKND2D2 g1020__1179 (.A1(DataIn[12]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_310));
   IOA22D2 g945__1180 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[31]),
	.B1(n_413),
	.B2(FE_PHN168_In_reg_30),
	.ZN(n_311));
   ND2D2 g1013__1206 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[26]),
	.ZN(n_335));
   ND2D2 g1009__1208 (.A1(FE_PHN346_FE_DBTN0_n_394),
	.A2(FE_OFN2_DatatobeSent_24),
	.ZN(n_336));
   ND2D2 g1034__1209 (.A1(DataIn[6]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_337));
   ND2D2 g1028__1210 (.A1(DataIn[4]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_338));
   ND2D2 g1011__1211 (.A1(DataIn[8]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_339));
   ND2D2 g1029__1212 (.A1(DataIn[2]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_340));
   ND2D2 g1017__1213 (.A1(FE_DBTN0_n_394),
	.A2(FE_OFN3_DatatobeSent_10),
	.ZN(n_341));
   ND2D2 g1015__1214 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[28]),
	.ZN(n_342));
   ND2D2 g1033__1215 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[5]),
	.ZN(n_343));
   ND2D2 g1021__1216 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[1]),
	.ZN(n_344));
   ND2D2 g1025__1217 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[15]),
	.ZN(n_345));
   ND2D2 g1018__1218 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[29]),
	.ZN(n_346));
   ND2D2 g1026__1221 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[3]),
	.ZN(n_349));
   CKND2D2 g1027__1222 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[16]),
	.ZN(n_350));
   CKND2D2 g1019__1223 (.A1(DataIn[11]),
	.A2(FE_DBTN0_n_394),
	.ZN(n_351));
   CKND2D2 g1024__1224 (.A1(FE_DBTN0_n_394),
	.A2(DataIn[14]),
	.ZN(n_352));
   ND3D8 g30 (.A1(n_390),
	.A2(n_404),
	.A3(FE_PHN244_n_407),
	.ZN(n_394));
   INR2D4 g33 (.A1(FE_PHN102_counter_0),
	.B1(FE_PHN100_counter_1),
	.ZN(FE_PHN265_n_390));
   INR2XD2 g17 (.A1(n_407),
	.B1(n_399),
	.ZN(n_400));
   IND2D4 g18 (.A1(counter[1]),
	.B1(n_163),
	.ZN(n_399));
   CKND6 g19 (.I(counter[0]),
	.ZN(n_163));
   INR2XD4 g15 (.A1(FE_PHN139_n_405),
	.B1(FE_PHN191_counter_3),
	.ZN(n_404));
   INR2XD1 g21 (.A1(FE_PHN139_n_405),
	.B1(FE_PSN250_counter_3),
	.ZN(n_406));
   INVD2 g22 (.I(CTS_12),
	.ZN(n_405));
   CKND3 g23 (.I(counter[2]),
	.ZN(n_407));
   CKND12 g6 (.I(n_76),
	.ZN(DataOut));
   MUX2D4 g1269 (.I0(DataIn[30]),
	.I1(FE_PHN134_In_reg_29),
	.S(n_394),
	.Z(n_410));
   AO22D4 g1270 (.A1(FE_PHN234_n_394),
	.A2(FE_PHN258_In_reg_20),
	.B1(FE_DBTN0_n_394),
	.B2(DataIn[21]),
	.Z(n_411));
   AO22D4 g1271 (.A1(FE_PHN236_n_394),
	.A2(FE_PHN297_In_reg_19),
	.B1(FE_DBTN0_n_394),
	.B2(DataIn[20]),
	.Z(n_412));
   AN3D2 g1272 (.A1(n_390),
	.A2(n_406),
	.A3(FE_PHN249_n_407),
	.Z(n_413));
endmodule

module DMRO (
	CLKBit, 
	CLKWord, 
	RSTn, 
	REVData, 
	REVCLK, 
	ENScr, 
	TestMode, 
	DataIn, 
	DataOut);
   input CLKBit;
   input CLKWord;
   input RSTn;
   input REVData;
   input REVCLK;
   input ENScr;
   input TestMode;
   input [29:0] DataIn;
   output DataOut;

   // Internal wires
   wire FE_PHN251_INS_SCR30b_DataOutSCR_6;
   wire FE_PHN67_n_28;
   wire FE_PHN66_INS_SCR30b_DataOutSCR_2;
   wire FE_PHN65_n_27;
   wire FE_PHN64_n_30;
   wire FE_PHN63_INS_SCR30b_S_reg_36;
   wire FE_PHN62_n_25;
   wire FE_PHN61_INS_SCR30b_DataOutSCR_0;
   wire FE_PHN60_DataPRBS7_25;
   wire FE_PHN59_n_22;
   wire FE_PHN58_n_55;
   wire FE_PHN57_INS_SCR30b_S_wire_46;
   wire FE_PHN56_INS_SCR30b_S_wire_48;
   wire FE_PHN55_INS_SCR30b_S_wire_54;
   wire FE_PHN54_INS_SCR30b_S_wire_50;
   wire FE_PHN53_INS_SCR30b_S_wire_52;
   wire FE_PHN52_INS_SCR30b_S_wire_42;
   wire FE_PHN51_INS_SCR30b_S_wire_44;
   wire FE_PHN50_INS_SCR30b_S_wire_56;
   wire FE_PHN49_INS_SCR30b_S_wire_39;
   wire FE_PHN48_INS_SCR30b_S_wire_40;
   wire FE_PHN47_INS_SCR30b_S_wire_55;
   wire FE_PHN46_INS_SCR30b_S_wire_47;
   wire FE_PHN45_INS_SCR30b_S_wire_53;
   wire FE_PHN44_INS_SCR30b_S_wire_51;
   wire FE_PHN43_INS_SCR30b_S_reg_8;
   wire FE_PHN42_INS_SCR30b_S_wire_43;
   wire FE_PHN41_INS_SCR30b_S_wire_45;
   wire FE_PHN40_INS_SCR30b_S_wire_49;
   wire FE_PHN39_INS_SCR30b_S_reg_3;
   wire FE_PHN38_INS_SCR30b_S_wire_41;
   wire FE_PHN37_INS_SCR30b_S_wire_57;
   wire FE_PHN36_INS_SCR30b_S_reg_4;
   wire FE_PHN35_INS_SCR30b_S_reg_5;
   wire FE_PHN34_INS_SCR30b_S_reg_2;
   wire FE_PHN33_INS_SCR30b_S_reg_1;
   wire FE_PHN32_INS_SCR30b_S_reg_7;
   wire FE_PHN31_INS_SCR30b_S_reg_0;
   wire FE_PHN30_INS_SCR30b_S_reg_6;
   wire FE_OFN29_DataOut;
   wire FE_OFN28_DataOut;
   wire FE_OFN27_n_170;
   wire FE_OFN26_rst_int;
   wire FE_OFN25_rst_int;
   wire FE_OFN24_rst_int;
   wire FE_OFN23_rst_int;
   wire FE_OFN22_rst_int;
   wire FE_OFN21_n_165;
   wire FE_OFN20_n_163;
   wire FE_OFN19_n_161;
   wire FE_OFN18_n_157;
   wire FE_OFN17_n_155;
   wire FE_OFN16_n_153;
   wire FE_OFN15_n_136;
   wire FE_OFN14_n_125;
   wire FE_OFN13_n_118;
   wire FE_OFN12_n_115;
   wire FE_OFN11_n_58;
   wire FE_OFN10_n_48;
   wire FE_OFN9_n_43;
   wire FE_OFN8_n_41;
   wire FE_OFN7_DataPRBS7_29;
   wire FE_OFN6_DataPRBS7_30;
   wire FE_OFN5_DataPRBS7_31;
   wire FE_OFN1_DataOut;
   wire FE_OFN0_DataOut;
   wire LTIEHI_NET;
   wire [31:0] DatatobeSent;
   wire [31:0] DataPRBS7;
   wire [29:0] INS_SCR30b_DataOutSCR;
   wire [57:0] INS_SCR30b_S_wire;
   wire [57:0] INS_SCR30b_S_reg;
   wire [29:0] INS_SCR30b_reg_input;
   wire CLKWordINT;
   wire INS_PRBS7Gen32b_n_12;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_78;
   wire n_79;
   wire n_110;
   wire n_112;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_118;
   wire n_120;
   wire n_122;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_128;
   wire n_130;
   wire n_132;
   wire n_134;
   wire n_136;
   wire n_138;
   wire n_139;
   wire n_142;
   wire n_144;
   wire n_146;
   wire n_147;
   wire n_150;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_210;
   wire n_211;
   wire n_213;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire rst_int;

   BUFFD1 FE_PHC251_INS_SCR30b_DataOutSCR_6 (.I(INS_SCR30b_DataOutSCR[6]),
	.Z(FE_PHN251_INS_SCR30b_DataOutSCR_6));
   BUFFD1 FE_PHC67_n_28 (.I(n_28),
	.Z(FE_PHN67_n_28));
   BUFFD1 FE_PHC66_INS_SCR30b_DataOutSCR_2 (.I(INS_SCR30b_DataOutSCR[2]),
	.Z(FE_PHN66_INS_SCR30b_DataOutSCR_2));
   BUFFD1 FE_PHC65_n_27 (.I(n_27),
	.Z(FE_PHN65_n_27));
   BUFFD1 FE_PHC64_n_30 (.I(n_30),
	.Z(FE_PHN64_n_30));
   BUFFD1 FE_PHC63_INS_SCR30b_S_reg_36 (.I(INS_SCR30b_S_reg[36]),
	.Z(FE_PHN63_INS_SCR30b_S_reg_36));
   BUFFD1 FE_PHC62_n_25 (.I(n_25),
	.Z(FE_PHN62_n_25));
   BUFFD1 FE_PHC61_INS_SCR30b_DataOutSCR_0 (.I(INS_SCR30b_DataOutSCR[0]),
	.Z(FE_PHN61_INS_SCR30b_DataOutSCR_0));
   BUFFD1 FE_PHC60_DataPRBS7_25 (.I(DataPRBS7[25]),
	.Z(FE_PHN60_DataPRBS7_25));
   BUFFD1 FE_PHC59_n_22 (.I(n_22),
	.Z(FE_PHN59_n_22));
   BUFFD1 FE_PHC58_n_55 (.I(n_55),
	.Z(FE_PHN58_n_55));
   DEL01 FE_PHC57_INS_SCR30b_S_wire_46 (.I(INS_SCR30b_S_wire[46]),
	.Z(FE_PHN57_INS_SCR30b_S_wire_46));
   DEL01 FE_PHC56_INS_SCR30b_S_wire_48 (.I(INS_SCR30b_S_wire[48]),
	.Z(FE_PHN56_INS_SCR30b_S_wire_48));
   DEL01 FE_PHC55_INS_SCR30b_S_wire_54 (.I(INS_SCR30b_S_wire[54]),
	.Z(FE_PHN55_INS_SCR30b_S_wire_54));
   DEL01 FE_PHC54_INS_SCR30b_S_wire_50 (.I(INS_SCR30b_S_wire[50]),
	.Z(FE_PHN54_INS_SCR30b_S_wire_50));
   DEL01 FE_PHC53_INS_SCR30b_S_wire_52 (.I(INS_SCR30b_S_wire[52]),
	.Z(FE_PHN53_INS_SCR30b_S_wire_52));
   DEL01 FE_PHC52_INS_SCR30b_S_wire_42 (.I(INS_SCR30b_S_wire[42]),
	.Z(FE_PHN52_INS_SCR30b_S_wire_42));
   DEL01 FE_PHC51_INS_SCR30b_S_wire_44 (.I(INS_SCR30b_S_wire[44]),
	.Z(FE_PHN51_INS_SCR30b_S_wire_44));
   DEL01 FE_PHC50_INS_SCR30b_S_wire_56 (.I(INS_SCR30b_S_wire[56]),
	.Z(FE_PHN50_INS_SCR30b_S_wire_56));
   DEL01 FE_PHC49_INS_SCR30b_S_wire_39 (.I(INS_SCR30b_S_wire[39]),
	.Z(FE_PHN49_INS_SCR30b_S_wire_39));
   DEL01 FE_PHC48_INS_SCR30b_S_wire_40 (.I(INS_SCR30b_S_wire[40]),
	.Z(FE_PHN48_INS_SCR30b_S_wire_40));
   DEL01 FE_PHC47_INS_SCR30b_S_wire_55 (.I(INS_SCR30b_S_wire[55]),
	.Z(FE_PHN47_INS_SCR30b_S_wire_55));
   DEL01 FE_PHC46_INS_SCR30b_S_wire_47 (.I(INS_SCR30b_S_wire[47]),
	.Z(FE_PHN46_INS_SCR30b_S_wire_47));
   DEL01 FE_PHC45_INS_SCR30b_S_wire_53 (.I(INS_SCR30b_S_wire[53]),
	.Z(FE_PHN45_INS_SCR30b_S_wire_53));
   DEL01 FE_PHC44_INS_SCR30b_S_wire_51 (.I(INS_SCR30b_S_wire[51]),
	.Z(FE_PHN44_INS_SCR30b_S_wire_51));
   DEL01 FE_PHC43_INS_SCR30b_S_reg_8 (.I(INS_SCR30b_S_reg[8]),
	.Z(FE_PHN43_INS_SCR30b_S_reg_8));
   DEL01 FE_PHC42_INS_SCR30b_S_wire_43 (.I(INS_SCR30b_S_wire[43]),
	.Z(FE_PHN42_INS_SCR30b_S_wire_43));
   DEL01 FE_PHC41_INS_SCR30b_S_wire_45 (.I(INS_SCR30b_S_wire[45]),
	.Z(FE_PHN41_INS_SCR30b_S_wire_45));
   DEL01 FE_PHC40_INS_SCR30b_S_wire_49 (.I(INS_SCR30b_S_wire[49]),
	.Z(FE_PHN40_INS_SCR30b_S_wire_49));
   DEL01 FE_PHC39_INS_SCR30b_S_reg_3 (.I(INS_SCR30b_S_reg[3]),
	.Z(FE_PHN39_INS_SCR30b_S_reg_3));
   DEL01 FE_PHC38_INS_SCR30b_S_wire_41 (.I(INS_SCR30b_S_wire[41]),
	.Z(FE_PHN38_INS_SCR30b_S_wire_41));
   DEL01 FE_PHC37_INS_SCR30b_S_wire_57 (.I(INS_SCR30b_S_wire[57]),
	.Z(FE_PHN37_INS_SCR30b_S_wire_57));
   DEL01 FE_PHC36_INS_SCR30b_S_reg_4 (.I(INS_SCR30b_S_reg[4]),
	.Z(FE_PHN36_INS_SCR30b_S_reg_4));
   DEL01 FE_PHC35_INS_SCR30b_S_reg_5 (.I(INS_SCR30b_S_reg[5]),
	.Z(FE_PHN35_INS_SCR30b_S_reg_5));
   DEL01 FE_PHC34_INS_SCR30b_S_reg_2 (.I(INS_SCR30b_S_reg[2]),
	.Z(FE_PHN34_INS_SCR30b_S_reg_2));
   DEL01 FE_PHC33_INS_SCR30b_S_reg_1 (.I(INS_SCR30b_S_reg[1]),
	.Z(FE_PHN33_INS_SCR30b_S_reg_1));
   DEL01 FE_PHC32_INS_SCR30b_S_reg_7 (.I(INS_SCR30b_S_reg[7]),
	.Z(FE_PHN32_INS_SCR30b_S_reg_7));
   DEL01 FE_PHC31_INS_SCR30b_S_reg_0 (.I(INS_SCR30b_S_reg[0]),
	.Z(FE_PHN31_INS_SCR30b_S_reg_0));
   DEL01 FE_PHC30_INS_SCR30b_S_reg_6 (.I(INS_SCR30b_S_reg[6]),
	.Z(FE_PHN30_INS_SCR30b_S_reg_6));
   CKND16 FE_OFC29_DataOut (.I(FE_OFN29_DataOut),
	.ZN(DataOut));
   INVD6 FE_OFC28_DataOut (.I(FE_OFN28_DataOut),
	.ZN(FE_OFN29_DataOut));
   CKBD4 FE_OFC27_n_170 (.I(n_170),
	.Z(FE_OFN27_n_170));
   BUFFD6 FE_OFC26_rst_int (.I(FE_OFN25_rst_int),
	.Z(FE_OFN26_rst_int));
   BUFFD6 FE_OFC25_rst_int (.I(FE_OFN24_rst_int),
	.Z(FE_OFN25_rst_int));
   CKBD3 FE_OFC24_rst_int (.I(FE_OFN23_rst_int),
	.Z(FE_OFN24_rst_int));
   BUFFD6 FE_OFC23_rst_int (.I(FE_OFN22_rst_int),
	.Z(FE_OFN23_rst_int));
   BUFFD6 FE_OFC22_rst_int (.I(rst_int),
	.Z(FE_OFN22_rst_int));
   CKBD3 FE_OFC21_n_165 (.I(n_165),
	.Z(FE_OFN21_n_165));
   CKBD3 FE_OFC20_n_163 (.I(n_163),
	.Z(FE_OFN20_n_163));
   CKBD3 FE_OFC19_n_161 (.I(n_161),
	.Z(FE_OFN19_n_161));
   CKBD3 FE_OFC18_n_157 (.I(n_157),
	.Z(FE_OFN18_n_157));
   CKBD3 FE_OFC17_n_155 (.I(n_155),
	.Z(FE_OFN17_n_155));
   CKBD3 FE_OFC16_n_153 (.I(n_153),
	.Z(FE_OFN16_n_153));
   CKBD3 FE_OFC15_n_136 (.I(n_136),
	.Z(FE_OFN15_n_136));
   CKBD3 FE_OFC14_n_125 (.I(n_125),
	.Z(FE_OFN14_n_125));
   CKBD3 FE_OFC13_n_118 (.I(n_118),
	.Z(FE_OFN13_n_118));
   CKBD3 FE_OFC12_n_115 (.I(n_115),
	.Z(FE_OFN12_n_115));
   CKBD3 FE_OFC11_n_58 (.I(n_58),
	.Z(FE_OFN11_n_58));
   BUFFD6 FE_OFC10_n_48 (.I(n_48),
	.Z(FE_OFN10_n_48));
   CKBD3 FE_OFC9_n_43 (.I(n_43),
	.Z(FE_OFN9_n_43));
   CKBD3 FE_OFC8_n_41 (.I(n_41),
	.Z(FE_OFN8_n_41));
   CKBD3 FE_OFC7_DataPRBS7_29 (.I(DataPRBS7[29]),
	.Z(FE_OFN7_DataPRBS7_29));
   CKBD3 FE_OFC6_DataPRBS7_30 (.I(DataPRBS7[30]),
	.Z(FE_OFN6_DataPRBS7_30));
   CKBD3 FE_OFC5_DataPRBS7_31 (.I(DataPRBS7[31]),
	.Z(FE_OFN5_DataPRBS7_31));
   CKND12 FE_OFC1_DataOut (.I(FE_OFN1_DataOut),
	.ZN(FE_OFN28_DataOut));
   INVD6 FE_OFC0_DataOut (.I(FE_OFN0_DataOut),
	.ZN(FE_OFN1_DataOut));
   TIEH LTIEHI (.Z(LTIEHI_NET));
   SER32b INS_SER32b (.CLKBit(CLKBit),
	.RSTn(FE_OFN25_rst_int),
	.DataIn({ DatatobeSent[31],
		DatatobeSent[30],
		DatatobeSent[29],
		DatatobeSent[28],
		DatatobeSent[27],
		DatatobeSent[26],
		DatatobeSent[25],
		DatatobeSent[24],
		DatatobeSent[23],
		DatatobeSent[22],
		DatatobeSent[21],
		DatatobeSent[20],
		DatatobeSent[19],
		n_230,
		DatatobeSent[17],
		n_229,
		DatatobeSent[15],
		DatatobeSent[14],
		DatatobeSent[13],
		DatatobeSent[12],
		DatatobeSent[11],
		DatatobeSent[10],
		DatatobeSent[9],
		DatatobeSent[8],
		DatatobeSent[7],
		DatatobeSent[6],
		DatatobeSent[5],
		n_231,
		DatatobeSent[3],
		DatatobeSent[2],
		DatatobeSent[1],
		DatatobeSent[0] }),
	.CLKWord(CLKWordINT),
	.DataOut(FE_OFN0_DataOut),
	.FE_OFN0_rst_int(FE_OFN26_rst_int));
   DFSNQD4 \INS_PRBS7Gen32b_SA_reg[0]  (.CP(CLKWordINT),
	.D(n_56),
	.Q(DataPRBS7[31]),
	.SDN(FE_OFN26_rst_int));
   DFSNQD1 \INS_PRBS7Gen32b_SA_reg[6]  (.CP(CLKWordINT),
	.D(n_52),
	.Q(DataPRBS7[25]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD1 \INS_PRBS7Gen32b_SA_reg[1]  (.CP(CLKWordINT),
	.D(FE_PHN58_n_55),
	.Q(DataPRBS7[30]),
	.SDN(FE_OFN26_rst_int));
   DFSNQD1 \INS_PRBS7Gen32b_SA_reg[2]  (.CP(CLKWordINT),
	.D(n_54),
	.Q(DataPRBS7[29]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD2 \INS_PRBS7Gen32b_SA_reg[5]  (.CP(CLKWordINT),
	.D(n_53),
	.Q(DataPRBS7[26]),
	.SDN(FE_OFN26_rst_int));
   XOR2D1 g1371__5266 (.A1(DataPRBS7[23]),
	.A2(DataPRBS7[27]),
	.Z(n_56));
   XOR2D1 g1372__2250 (.A1(DataPRBS7[22]),
	.A2(DataPRBS7[26]),
	.Z(n_55));
   CKXOR2D1 g1373__6083 (.A1(DataPRBS7[21]),
	.A2(FE_PHN60_DataPRBS7_25),
	.Z(n_54));
   CKXOR2D1 g1374__2703 (.A1(DataPRBS7[10]),
	.A2(FE_PHN60_DataPRBS7_25),
	.Z(n_53));
   XOR2D1 g1375__5795 (.A1(DataPRBS7[21]),
	.A2(DataPRBS7[17]),
	.Z(n_52));
   DFCNQD1 \INS_SCR30b_S_reg_reg[15]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[14]),
	.Q(INS_SCR30b_S_wire[45]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[9]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[20]),
	.Q(INS_SCR30b_S_wire[39]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[11]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[18]),
	.Q(INS_SCR30b_S_wire[41]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[13]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[16]),
	.Q(INS_SCR30b_S_wire[43]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[0]  (.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[29]),
	.Q(INS_SCR30b_S_reg[0]),
	.SDN(FE_OFN25_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[17]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[12]),
	.Q(INS_SCR30b_S_wire[47]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[19]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[10]),
	.Q(INS_SCR30b_S_wire[49]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[21]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[8]),
	.Q(INS_SCR30b_S_wire[51]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[35]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN35_INS_SCR30b_S_reg_5),
	.Q(INS_SCR30b_S_reg[35]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[27]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN66_INS_SCR30b_DataOutSCR_2),
	.Q(INS_SCR30b_S_wire[57]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[29]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN61_INS_SCR30b_DataOutSCR_0),
	.Q(INS_SCR30b_S_reg[29]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[33]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN39_INS_SCR30b_S_reg_3),
	.Q(INS_SCR30b_S_reg[33]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[25]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[4]),
	.Q(INS_SCR30b_S_wire[55]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[37]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN32_INS_SCR30b_S_reg_7),
	.Q(INS_SCR30b_S_reg[37]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[31]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN33_INS_SCR30b_S_reg_1),
	.Q(INS_SCR30b_S_reg[31]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[23]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN251_INS_SCR30b_DataOutSCR_6),
	.Q(INS_SCR30b_S_wire[53]));
   IND2D0 g1316__5019 (.A1(REVCLK),
	.B1(CLKWord),
	.ZN(n_79));
   IND3D4 g1807__1857 (.A1(DataPRBS7[27]),
	.B1(TestMode),
	.B2(n_51),
	.ZN(n_120));
   MOAI22D0 g1810__4296 (.A1(n_46),
	.A2(n_49),
	.B1(n_180),
	.B2(FE_OFN10_n_48),
	.ZN(n_147));
   MOAI22D0 g1811__3772 (.A1(n_45),
	.A2(n_44),
	.B1(n_181),
	.B2(FE_OFN10_n_48),
	.ZN(n_126));
   MOAI22D0 g1813__4547 (.A1(FE_OFN9_n_43),
	.A2(n_44),
	.B1(n_189),
	.B2(FE_OFN10_n_48),
	.ZN(n_128));
   CKND2D0 g1815__2683 (.A1(n_42),
	.A2(n_47),
	.ZN(n_144));
   AO22D0 g1817__6877 (.A1(n_204),
	.A2(FE_OFN10_n_48),
	.B1(FE_OFN8_n_41),
	.B2(INS_PRBS7Gen32b_n_12),
	.Z(n_112));
   AO22D0 g1820__7675 (.A1(n_184),
	.A2(FE_OFN10_n_48),
	.B1(FE_OFN8_n_41),
	.B2(DataPRBS7[24]),
	.Z(n_139));
   CKND2D0 g1821__7118 (.A1(n_42),
	.A2(n_50),
	.ZN(n_150));
   MOAI22D0 g1822__8757 (.A1(FE_OFN6_DataPRBS7_30),
	.A2(n_166),
	.B1(n_179),
	.B2(FE_OFN10_n_48),
	.ZN(n_116));
   MOAI22D0 g1823__1786 (.A1(n_40),
	.A2(n_44),
	.B1(n_203),
	.B2(FE_OFN10_n_48),
	.ZN(n_132));
   AO22D0 g1825__5703 (.A1(n_178),
	.A2(FE_OFN10_n_48),
	.B1(n_39),
	.B2(FE_OFN6_DataPRBS7_30),
	.Z(n_130));
   MOAI22D0 g1827__5266 (.A1(DataPRBS7[28]),
	.A2(n_154),
	.B1(n_183),
	.B2(FE_OFN10_n_48),
	.ZN(n_110));
   MOAI22D0 g1830__2703 (.A1(n_38),
	.A2(n_44),
	.B1(n_196),
	.B2(FE_OFN10_n_48),
	.ZN(n_134));
   IND2D0 g1833__1840 (.A1(n_160),
	.B1(FE_OFN9_n_43),
	.ZN(n_122));
   IND2D0 g1839__3772 (.A1(FE_OFN7_DataPRBS7_29),
	.B1(n_42),
	.ZN(n_146));
   IND2D0 g1840__1474 (.A1(DataPRBS7[26]),
	.B1(n_42),
	.ZN(n_138));
   IND2D0 g1841__4547 (.A1(DataPRBS7[23]),
	.B1(n_42),
	.ZN(n_142));
   CKND2D0 g1842__9682 (.A1(n_42),
	.A2(FE_OFN9_n_43),
	.ZN(n_152));
   CKND2D0 g1844__1309 (.A1(FE_OFN10_n_48),
	.A2(n_190),
	.ZN(n_165));
   CKND2D0 g1845__6877 (.A1(FE_OFN10_n_48),
	.A2(n_188),
	.ZN(n_115));
   CKND2D0 g1846__2900 (.A1(FE_OFN10_n_48),
	.A2(n_195),
	.ZN(n_118));
   CKND2D0 g1847__2391 (.A1(FE_OFN10_n_48),
	.A2(n_198),
	.ZN(n_153));
   CKND2D0 g1848__7675 (.A1(FE_OFN10_n_48),
	.A2(n_197),
	.ZN(n_155));
   CKND2D0 g1849__7118 (.A1(FE_OFN10_n_48),
	.A2(n_201),
	.ZN(n_125));
   CKND2D0 g1850__8757 (.A1(FE_OFN10_n_48),
	.A2(n_182),
	.ZN(n_157));
   CKND2D0 g1851__1786 (.A1(FE_OFN10_n_48),
	.A2(n_193),
	.ZN(n_159));
   CKND2D0 g1852__5953 (.A1(FE_OFN10_n_48),
	.A2(n_205),
	.ZN(n_161));
   CKND2D0 g1853__5703 (.A1(FE_OFN10_n_48),
	.A2(n_200),
	.ZN(n_136));
   CKND2D0 g1854__7114 (.A1(FE_OFN10_n_48),
	.A2(n_192),
	.ZN(n_163));
   ND3D0 g1855__5266 (.A1(FE_OFN9_n_43),
	.A2(FE_OFN5_DataPRBS7_31),
	.A3(TestMode),
	.ZN(n_124));
   INVD2 g1861 (.I(n_169),
	.ZN(n_42));
   CKND2D0 g1862__2250 (.A1(TestMode),
	.A2(DataPRBS7[17]),
	.ZN(n_156));
   CKND2D0 g1863__6083 (.A1(TestMode),
	.A2(DataPRBS7[22]),
	.ZN(n_162));
   CKND2D0 g1864__2703 (.A1(TestMode),
	.A2(DataPRBS7[23]),
	.ZN(n_158));
   CKND2D0 g1865__5795 (.A1(TestMode),
	.A2(DataPRBS7[10]),
	.ZN(n_114));
   CKAN2D0 g1866__7344 (.A1(FE_OFN6_DataPRBS7_30),
	.A2(TestMode),
	.Z(DatatobeSent[30]));
   CKND2D2 g1867__1840 (.A1(TestMode),
	.A2(DataPRBS7[27]),
	.ZN(n_167));
   CKND2D0 g1868__5019 (.A1(TestMode),
	.A2(DataPRBS7[25]),
	.ZN(n_169));
   INR2D1 g1869__1857 (.A1(n_36),
	.B1(ENScr),
	.ZN(n_48));
   INVD1 g1870 (.I(n_44),
	.ZN(n_39));
   INVD1 g1871 (.I(n_168),
	.ZN(n_37));
   CKND1 g1872 (.I(FE_OFN8_n_41),
	.ZN(n_49));
   ND2D1 g1873__9906 (.A1(ENScr),
	.A2(n_36),
	.ZN(n_170));
   CKND2D0 g1874__8780 (.A1(TestMode),
	.A2(DataPRBS7[21]),
	.ZN(n_164));
   IND2D0 g1875__4296 (.A1(FE_OFN5_DataPRBS7_31),
	.B1(TestMode),
	.ZN(DatatobeSent[31]));
   CKND2D1 g1876__3772 (.A1(TestMode),
	.A2(DataPRBS7[24]),
	.ZN(n_154));
   CKND2D0 g1877__1474 (.A1(TestMode),
	.A2(FE_OFN7_DataPRBS7_29),
	.ZN(n_160));
   CKND2D2 g1878__4547 (.A1(TestMode),
	.A2(DataPRBS7[28]),
	.ZN(n_166));
   IND2D2 g1879__9682 (.A1(DataPRBS7[26]),
	.B1(TestMode),
	.ZN(n_44));
   ND2D2 g1880__2683 (.A1(TestMode),
	.A2(DataPRBS7[26]),
	.ZN(n_168));
   INR2D0 g1881__1309 (.A1(TestMode),
	.B1(DataPRBS7[25]),
	.ZN(n_41));
   CKND1 g1884 (.I(TestMode),
	.ZN(n_36));
   XOR2D0 g1858__6877 (.A1(DataPRBS7[28]),
	.A2(DataPRBS7[23]),
	.Z(n_51));
   XNR2D0 g1856__2900 (.A1(DataPRBS7[26]),
	.A2(DataPRBS7[17]),
	.ZN(n_50));
   XNR2D0 g1859__2391 (.A1(DataPRBS7[26]),
	.A2(DataPRBS7[21]),
	.ZN(n_47));
   XOR2D0 g1857__7675 (.A1(FE_OFN5_DataPRBS7_31),
	.A2(n_40),
	.Z(n_46));
   XOR2D0 g1860__7118 (.A1(FE_OFN9_n_43),
	.A2(DataPRBS7[22]),
	.Z(n_45));
   CKND1 g1882 (.I(DataPRBS7[24]),
	.ZN(n_38));
   XOR3D1 g1801__8757 (.A1(DataPRBS7[26]),
	.A2(DataPRBS7[27]),
	.A3(DataPRBS7[24]),
	.Z(INS_PRBS7Gen32b_n_12));
   CKXOR2D1 g1802__1786 (.A1(DataPRBS7[22]),
	.A2(DataPRBS7[24]),
	.Z(DataPRBS7[10]));
   XOR2D1 g2743__7114 (.A1(DataPRBS7[27]),
	.A2(DataPRBS7[28]),
	.Z(DataPRBS7[21]));
   CKXOR2D1 g2744__5266 (.A1(FE_OFN7_DataPRBS7_29),
	.A2(FE_OFN5_DataPRBS7_31),
	.Z(DataPRBS7[17]));
   XOR2D1 g2745__2250 (.A1(FE_OFN7_DataPRBS7_29),
	.A2(FE_OFN6_DataPRBS7_30),
	.Z(DataPRBS7[23]));
   CKXOR2D1 g2746__6083 (.A1(FE_OFN7_DataPRBS7_29),
	.A2(DataPRBS7[28]),
	.Z(DataPRBS7[22]));
   XOR2D1 g2747__2703 (.A1(FE_OFN6_DataPRBS7_30),
	.A2(FE_OFN5_DataPRBS7_31),
	.Z(DataPRBS7[24]));
   INVD4 g2748 (.I(REVData),
	.ZN(n_78));
   DFSNQD1 \INS_SCR30b_S_reg_reg[2]  (.CP(CLKWordINT),
	.D(n_35),
	.Q(INS_SCR30b_S_reg[2]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[4]  (.CP(CLKWordINT),
	.D(n_34),
	.Q(INS_SCR30b_S_reg[4]),
	.SDN(FE_OFN24_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[6]  (.CP(CLKWordINT),
	.D(n_33),
	.Q(INS_SCR30b_S_reg[6]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[8]  (.CP(CLKWordINT),
	.D(n_32),
	.Q(INS_SCR30b_S_reg[8]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[10]  (.CP(CLKWordINT),
	.D(n_31),
	.Q(INS_SCR30b_S_wire[40]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[12]  (.CP(CLKWordINT),
	.D(FE_PHN64_n_30),
	.Q(INS_SCR30b_S_wire[42]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[14]  (.CP(CLKWordINT),
	.D(n_29),
	.Q(INS_SCR30b_S_wire[44]),
	.SDN(FE_OFN24_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[16]  (.CP(CLKWordINT),
	.D(FE_PHN67_n_28),
	.Q(INS_SCR30b_S_wire[46]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[18]  (.CP(CLKWordINT),
	.D(FE_PHN65_n_27),
	.Q(INS_SCR30b_S_wire[48]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[20]  (.CP(CLKWordINT),
	.D(n_26),
	.Q(INS_SCR30b_S_wire[50]),
	.SDN(FE_OFN24_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[22]  (.CP(CLKWordINT),
	.D(FE_PHN62_n_25),
	.Q(INS_SCR30b_S_wire[52]),
	.SDN(FE_OFN24_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[24]  (.CP(CLKWordINT),
	.D(n_24),
	.Q(INS_SCR30b_S_wire[54]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[26]  (.CP(CLKWordINT),
	.D(n_23),
	.Q(INS_SCR30b_S_wire[56]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[28]  (.CP(CLKWordINT),
	.D(FE_PHN59_n_22),
	.Q(INS_SCR30b_S_reg[28]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[30]  (.CP(CLKWordINT),
	.D(FE_PHN31_INS_SCR30b_S_reg_0),
	.Q(INS_SCR30b_S_reg[30]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[32]  (.CP(CLKWordINT),
	.D(FE_PHN34_INS_SCR30b_S_reg_2),
	.Q(INS_SCR30b_S_reg[32]),
	.SDN(FE_OFN25_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[34]  (.CP(CLKWordINT),
	.D(FE_PHN36_INS_SCR30b_S_reg_4),
	.Q(INS_SCR30b_S_reg[34]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[36]  (.CP(CLKWordINT),
	.D(FE_PHN30_INS_SCR30b_S_reg_6),
	.Q(INS_SCR30b_S_reg[36]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_S_reg_reg[38]  (.CP(CLKWordINT),
	.D(FE_PHN43_INS_SCR30b_S_reg_8),
	.Q(INS_SCR30b_S_reg[38]),
	.SDN(FE_OFN23_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[39]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN49_INS_SCR30b_S_wire_39),
	.Q(INS_SCR30b_S_reg[39]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[40]  (.CP(CLKWordINT),
	.D(FE_PHN48_INS_SCR30b_S_wire_40),
	.Q(INS_SCR30b_S_reg[40]),
	.SDN(FE_OFN25_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[41]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN38_INS_SCR30b_S_wire_41),
	.Q(INS_SCR30b_S_reg[41]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[42]  (.CP(CLKWordINT),
	.D(FE_PHN52_INS_SCR30b_S_wire_42),
	.Q(INS_SCR30b_S_reg[42]),
	.SDN(FE_OFN25_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[43]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN42_INS_SCR30b_S_wire_43),
	.Q(INS_SCR30b_S_reg[43]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[44]  (.CP(CLKWordINT),
	.D(FE_PHN51_INS_SCR30b_S_wire_44),
	.Q(INS_SCR30b_S_reg[44]),
	.SDN(FE_OFN23_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[45]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN41_INS_SCR30b_S_wire_45),
	.Q(INS_SCR30b_S_reg[45]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[46]  (.CP(CLKWordINT),
	.D(FE_PHN57_INS_SCR30b_S_wire_46),
	.Q(INS_SCR30b_S_reg[46]),
	.SDN(FE_OFN23_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[47]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN46_INS_SCR30b_S_wire_47),
	.Q(INS_SCR30b_S_reg[47]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[48]  (.CP(CLKWordINT),
	.D(FE_PHN56_INS_SCR30b_S_wire_48),
	.Q(INS_SCR30b_S_reg[48]),
	.SDN(FE_OFN23_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[49]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN40_INS_SCR30b_S_wire_49),
	.Q(INS_SCR30b_S_reg[49]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[50]  (.CP(CLKWordINT),
	.D(FE_PHN54_INS_SCR30b_S_wire_50),
	.Q(INS_SCR30b_S_reg[50]),
	.SDN(FE_OFN24_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[51]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN44_INS_SCR30b_S_wire_51),
	.Q(INS_SCR30b_S_reg[51]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[52]  (.CP(CLKWordINT),
	.D(FE_PHN53_INS_SCR30b_S_wire_52),
	.Q(INS_SCR30b_S_reg[52]),
	.SDN(FE_OFN24_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[53]  (.CDN(FE_OFN24_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN45_INS_SCR30b_S_wire_53),
	.Q(INS_SCR30b_S_reg[53]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[54]  (.CP(CLKWordINT),
	.D(FE_PHN55_INS_SCR30b_S_wire_54),
	.Q(INS_SCR30b_S_reg[54]),
	.SDN(FE_OFN23_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[55]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN47_INS_SCR30b_S_wire_55),
	.Q(INS_SCR30b_S_reg[55]));
   DFSNQD1 \INS_SCR30b_S_reg_reg[56]  (.CP(CLKWordINT),
	.D(FE_PHN50_INS_SCR30b_S_wire_56),
	.Q(INS_SCR30b_S_reg[56]),
	.SDN(FE_OFN23_rst_int));
   DFCNQD1 \INS_SCR30b_S_reg_reg[57]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(FE_PHN37_INS_SCR30b_S_wire_57),
	.Q(INS_SCR30b_S_reg[57]));
   OAI211D1 g2573__5795 (.A1(FE_OFN27_n_170),
	.A2(n_21),
	.B(n_160),
	.C(FE_OFN19_n_161),
	.ZN(DatatobeSent[29]));
   OAI211D1 g2574__7344 (.A1(FE_OFN27_n_170),
	.A2(n_20),
	.B(n_114),
	.C(FE_OFN12_n_115),
	.ZN(DatatobeSent[10]));
   INVD1 g2575 (.I(n_20),
	.ZN(INS_SCR30b_DataOutSCR[10]));
   XNR3D1 g2576__1840 (.A1(INS_SCR30b_S_reg[47]),
	.A2(INS_SCR30b_S_reg[28]),
	.A3(n_188),
	.ZN(n_20));
   INVD1 g2577 (.I(n_21),
	.ZN(INS_SCR30b_DataOutSCR[29]));
   XNR3D1 g2578__5019 (.A1(INS_SCR30b_S_wire[39]),
	.A2(INS_SCR30b_S_reg[28]),
	.A3(n_205),
	.ZN(n_21));
   OAI211D1 g2579__1857 (.A1(FE_OFN27_n_170),
	.A2(n_19),
	.B(n_146),
	.C(n_210),
	.ZN(DatatobeSent[1]));
   AO211D1 g2581__9906 (.A1(INS_SCR30b_DataOutSCR[12]),
	.A2(FE_OFN11_n_58),
	.B(n_223),
	.C(n_134),
	.Z(DatatobeSent[12]));
   INVD1 g2582 (.I(n_19),
	.ZN(n_22));
   XNR3D1 g2583__8780 (.A1(INS_SCR30b_S_reg[37]),
	.A2(INS_SCR30b_S_reg[56]),
	.A3(n_194),
	.ZN(n_19));
   XOR3D1 g2584__4296 (.A1(FE_PHN50_INS_SCR30b_S_wire_56),
	.A2(INS_SCR30b_S_reg[45]),
	.A3(n_196),
	.Z(INS_SCR30b_DataOutSCR[12]));
   OAI211D1 g2586__3772 (.A1(FE_OFN27_n_170),
	.A2(n_18),
	.B(n_124),
	.C(n_226),
	.ZN(DatatobeSent[3]));
   AO211D1 g2588__1474 (.A1(INS_SCR30b_DataOutSCR[14]),
	.A2(FE_OFN11_n_58),
	.B(n_211),
	.C(n_132),
	.Z(DatatobeSent[14]));
   INVD1 g2589 (.I(n_18),
	.ZN(n_23));
   XNR3D1 g2590__4547 (.A1(INS_SCR30b_S_reg[35]),
	.A2(INS_SCR30b_S_reg[54]),
	.A3(n_202),
	.ZN(n_18));
   XOR3D1 g2591__9682 (.A1(FE_PHN55_INS_SCR30b_S_wire_54),
	.A2(INS_SCR30b_S_reg[43]),
	.A3(n_203),
	.Z(INS_SCR30b_DataOutSCR[14]));
   OAI211D2 g2593__2683 (.A1(FE_OFN27_n_170),
	.A2(n_17),
	.B(n_150),
	.C(n_219),
	.ZN(DatatobeSent[5]));
   INVD1 g2596 (.I(n_17),
	.ZN(n_24));
   XNR3D1 g2597__6877 (.A1(INS_SCR30b_S_reg[33]),
	.A2(INS_SCR30b_S_reg[52]),
	.A3(n_187),
	.ZN(n_17));
   XOR3D1 g2598__2900 (.A1(FE_PHN53_INS_SCR30b_S_wire_52),
	.A2(INS_SCR30b_S_reg[41]),
	.A3(n_179),
	.Z(INS_SCR30b_DataOutSCR[16]));
   OAI211D1 g2600__2391 (.A1(FE_OFN27_n_170),
	.A2(n_16),
	.B(n_144),
	.C(n_221),
	.ZN(DatatobeSent[7]));
   INVD1 g2603 (.I(n_16),
	.ZN(n_25));
   XNR3D1 g2604__7118 (.A1(INS_SCR30b_S_reg[31]),
	.A2(INS_SCR30b_S_reg[50]),
	.A3(n_206),
	.ZN(n_16));
   XOR3D1 g2605__8757 (.A1(FE_PHN54_INS_SCR30b_S_wire_50),
	.A2(INS_SCR30b_S_reg[39]),
	.A3(n_184),
	.Z(INS_SCR30b_DataOutSCR[18]));
   OAI211D2 g2607__1786 (.A1(FE_OFN27_n_170),
	.A2(n_15),
	.B(n_120),
	.C(n_215),
	.ZN(DatatobeSent[9]));
   AO211D1 g2609__5953 (.A1(INS_SCR30b_DataOutSCR[20]),
	.A2(FE_OFN11_n_58),
	.B(n_222),
	.C(n_128),
	.Z(DatatobeSent[20]));
   INVD1 g2610 (.I(n_15),
	.ZN(n_26));
   XNR3D1 g2611__5703 (.A1(INS_SCR30b_S_reg[29]),
	.A2(INS_SCR30b_S_reg[48]),
	.A3(n_185),
	.ZN(n_15));
   XOR3D1 g2612__7114 (.A1(FE_PHN56_INS_SCR30b_S_wire_48),
	.A2(INS_SCR30b_S_reg[37]),
	.A3(n_189),
	.Z(INS_SCR30b_DataOutSCR[20]));
   OAI211D1 g2614__5266 (.A1(FE_OFN27_n_170),
	.A2(n_14),
	.B(n_142),
	.C(n_216),
	.ZN(DatatobeSent[11]));
   OAI211D1 g2616__2250 (.A1(FE_OFN27_n_170),
	.A2(n_13),
	.B(n_162),
	.C(FE_OFN20_n_163),
	.ZN(DatatobeSent[22]));
   INVD1 g2617 (.I(n_14),
	.ZN(n_27));
   XNR3D1 g2618__6083 (.A1(INS_SCR30b_S_wire[57]),
	.A2(INS_SCR30b_S_reg[46]),
	.A3(n_191),
	.ZN(n_14));
   INVD1 g2619 (.I(n_13),
	.ZN(INS_SCR30b_DataOutSCR[22]));
   XNR3D1 g2620__2703 (.A1(INS_SCR30b_S_reg[35]),
	.A2(FE_PHN57_INS_SCR30b_S_wire_46),
	.A3(n_192),
	.ZN(n_13));
   OAI211D1 g2622__5795 (.A1(FE_OFN27_n_170),
	.A2(n_12),
	.B(n_152),
	.C(n_227),
	.ZN(DatatobeSent[13]));
   OAI211D1 g2624__7344 (.A1(FE_OFN27_n_170),
	.A2(n_11),
	.B(n_154),
	.C(FE_OFN17_n_155),
	.ZN(DatatobeSent[24]));
   INVD1 g2625 (.I(n_12),
	.ZN(n_28));
   XNR3D1 g2626__1840 (.A1(INS_SCR30b_S_wire[55]),
	.A2(INS_SCR30b_S_reg[44]),
	.A3(n_199),
	.ZN(n_12));
   INVD1 g2627 (.I(n_11),
	.ZN(INS_SCR30b_DataOutSCR[24]));
   XNR3D1 g2628__5019 (.A1(INS_SCR30b_S_reg[33]),
	.A2(FE_PHN51_INS_SCR30b_S_wire_44),
	.A3(n_197),
	.ZN(n_11));
   OAI211D1 g2630__1857 (.A1(FE_OFN27_n_170),
	.A2(n_10),
	.B(n_122),
	.C(n_217),
	.ZN(DatatobeSent[15]));
   OAI211D1 g2632__9906 (.A1(FE_OFN27_n_170),
	.A2(n_9),
	.B(n_168),
	.C(FE_OFN15_n_136),
	.ZN(DatatobeSent[26]));
   INVD1 g2633 (.I(n_10),
	.ZN(n_29));
   XNR3D1 g2634__8780 (.A1(INS_SCR30b_S_wire[53]),
	.A2(INS_SCR30b_S_reg[42]),
	.A3(n_207),
	.ZN(n_10));
   INVD1 g2635 (.I(n_9),
	.ZN(INS_SCR30b_DataOutSCR[26]));
   XNR3D1 g2636__4296 (.A1(INS_SCR30b_S_reg[31]),
	.A2(FE_PHN52_INS_SCR30b_S_wire_42),
	.A3(n_200),
	.ZN(n_9));
   OAI211D1 g2638__3772 (.A1(FE_OFN27_n_170),
	.A2(n_8),
	.B(n_156),
	.C(FE_OFN18_n_157),
	.ZN(DatatobeSent[17]));
   OAI211D1 g2640__1474 (.A1(FE_OFN27_n_170),
	.A2(n_7),
	.B(n_166),
	.C(FE_OFN13_n_118),
	.ZN(DatatobeSent[28]));
   INVD1 g2641 (.I(n_8),
	.ZN(n_30));
   XNR3D1 g2642__4547 (.A1(INS_SCR30b_S_wire[51]),
	.A2(INS_SCR30b_S_reg[40]),
	.A3(n_182),
	.ZN(n_8));
   INVD1 g2643 (.I(n_7),
	.ZN(INS_SCR30b_DataOutSCR[28]));
   XNR3D1 g2644__9682 (.A1(INS_SCR30b_S_reg[29]),
	.A2(INS_SCR30b_S_wire[40]),
	.A3(n_195),
	.ZN(n_7));
   OAI211D1 g2646__2683 (.A1(FE_OFN27_n_170),
	.A2(n_6),
	.B(n_138),
	.C(n_225),
	.ZN(DatatobeSent[19]));
   AO211D1 g2647__1309 (.A1(INS_SCR30b_DataOutSCR[0]),
	.A2(FE_OFN11_n_58),
	.B(n_218),
	.C(n_110),
	.Z(DatatobeSent[0]));
   INVD1 g2649 (.I(n_6),
	.ZN(n_31));
   XNR3D1 g2650__6877 (.A1(INS_SCR30b_S_wire[49]),
	.A2(INS_SCR30b_S_reg[38]),
	.A3(n_186),
	.ZN(n_6));
   XOR3D1 g2651__2900 (.A1(INS_SCR30b_S_reg[38]),
	.A2(INS_SCR30b_S_reg[57]),
	.A3(n_183),
	.Z(INS_SCR30b_DataOutSCR[0]));
   AO211D1 g2653__2391 (.A1(INS_SCR30b_DataOutSCR[2]),
	.A2(FE_OFN11_n_58),
	.B(n_213),
	.C(n_130),
	.Z(DatatobeSent[2]));
   OAI211D1 g2654__7675 (.A1(FE_OFN27_n_170),
	.A2(n_5),
	.B(n_164),
	.C(FE_OFN21_n_165),
	.ZN(DatatobeSent[21]));
   XOR3D1 g2656__7118 (.A1(FE_PHN63_INS_SCR30b_S_reg_36),
	.A2(INS_SCR30b_S_reg[55]),
	.A3(n_178),
	.Z(INS_SCR30b_DataOutSCR[2]));
   INVD1 g2657 (.I(n_5),
	.ZN(n_32));
   XNR3D1 g2658__8757 (.A1(INS_SCR30b_S_wire[47]),
	.A2(FE_PHN63_INS_SCR30b_S_reg_36),
	.A3(n_190),
	.ZN(n_5));
   OAI211D2 g2661__5953 (.A1(FE_OFN27_n_170),
	.A2(n_4),
	.B(n_158),
	.C(n_159),
	.ZN(DatatobeSent[23]));
   INVD1 g2663 (.I(n_4),
	.ZN(n_33));
   XNR3D1 g2664__5703 (.A1(INS_SCR30b_S_wire[45]),
	.A2(INS_SCR30b_S_reg[34]),
	.A3(n_193),
	.ZN(n_4));
   XOR3D1 g2665__7114 (.A1(INS_SCR30b_S_reg[34]),
	.A2(INS_SCR30b_S_reg[53]),
	.A3(n_180),
	.Z(INS_SCR30b_DataOutSCR[4]));
   AO211D1 g2667__5266 (.A1(INS_SCR30b_DataOutSCR[6]),
	.A2(FE_OFN11_n_58),
	.B(n_228),
	.C(n_112),
	.Z(DatatobeSent[6]));
   OAI211D1 g2668__2250 (.A1(FE_OFN27_n_170),
	.A2(n_3),
	.B(n_169),
	.C(FE_OFN16_n_153),
	.ZN(DatatobeSent[25]));
   XOR3D1 g2670__6083 (.A1(INS_SCR30b_S_reg[32]),
	.A2(INS_SCR30b_S_reg[51]),
	.A3(n_204),
	.Z(INS_SCR30b_DataOutSCR[6]));
   INVD1 g2671 (.I(n_3),
	.ZN(n_34));
   XNR3D1 g2672__2703 (.A1(INS_SCR30b_S_wire[43]),
	.A2(INS_SCR30b_S_reg[32]),
	.A3(n_198),
	.ZN(n_3));
   AO211D1 g2674__5795 (.A1(INS_SCR30b_DataOutSCR[8]),
	.A2(FE_OFN11_n_58),
	.B(n_220),
	.C(n_126),
	.Z(DatatobeSent[8]));
   OAI211D1 g2675__7344 (.A1(FE_OFN27_n_170),
	.A2(n_2),
	.B(n_167),
	.C(FE_OFN14_n_125),
	.ZN(DatatobeSent[27]));
   INVD1 g2677 (.I(n_2),
	.ZN(n_35));
   XNR3D1 g2678__1840 (.A1(INS_SCR30b_S_wire[41]),
	.A2(INS_SCR30b_S_reg[30]),
	.A3(n_201),
	.ZN(n_2));
   XOR3D1 g2679__5019 (.A1(INS_SCR30b_S_reg[30]),
	.A2(INS_SCR30b_S_reg[49]),
	.A3(n_181),
	.Z(INS_SCR30b_DataOutSCR[8]));
   CKND1 g2710 (.I(FE_OFN27_n_170),
	.ZN(n_58));
   XOR3D1 g2749__1857 (.A1(DataPRBS7[26]),
	.A2(DataPRBS7[25]),
	.A3(DataPRBS7[23]),
	.Z(n_1));
   DFCNQD1 rst_int_reg (.CDN(RSTn),
	.CP(n_0),
	.D(LTIEHI_NET),
	.Q(rst_int));
   OAI21D0 g2750__9906 (.A1(CLKWord),
	.A2(n_57),
	.B(n_79),
	.ZN(n_0));
   DFSNQD1 \INS_SCR30b_reg_input_reg[0]  (.CP(CLKWordINT),
	.D(DataIn[0]),
	.Q(INS_SCR30b_reg_input[0]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[4]  (.CP(CLKWordINT),
	.D(DataIn[4]),
	.Q(INS_SCR30b_reg_input[4]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[6]  (.CP(CLKWordINT),
	.D(DataIn[6]),
	.Q(INS_SCR30b_reg_input[6]),
	.SDN(FE_OFN23_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[8]  (.CP(CLKWordINT),
	.D(DataIn[8]),
	.Q(INS_SCR30b_reg_input[8]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[10]  (.CP(CLKWordINT),
	.D(DataIn[10]),
	.Q(INS_SCR30b_reg_input[10]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[12]  (.CP(CLKWordINT),
	.D(DataIn[12]),
	.Q(INS_SCR30b_reg_input[12]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[14]  (.CP(CLKWordINT),
	.D(DataIn[14]),
	.Q(INS_SCR30b_reg_input[14]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[16]  (.CP(CLKWordINT),
	.D(DataIn[16]),
	.Q(INS_SCR30b_reg_input[16]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[20]  (.CP(CLKWordINT),
	.D(DataIn[20]),
	.Q(INS_SCR30b_reg_input[20]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[22]  (.CP(CLKWordINT),
	.D(DataIn[22]),
	.Q(INS_SCR30b_reg_input[22]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[24]  (.CP(CLKWordINT),
	.D(DataIn[24]),
	.Q(INS_SCR30b_reg_input[24]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[2]  (.CP(CLKWordINT),
	.D(DataIn[2]),
	.Q(INS_SCR30b_reg_input[2]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[28]  (.CP(CLKWordINT),
	.D(DataIn[28]),
	.Q(INS_SCR30b_reg_input[28]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[18]  (.CP(CLKWordINT),
	.D(DataIn[18]),
	.Q(INS_SCR30b_reg_input[18]),
	.SDN(FE_OFN22_rst_int));
   DFSNQD1 \INS_SCR30b_reg_input_reg[26]  (.CP(CLKWordINT),
	.D(DataIn[26]),
	.Q(INS_SCR30b_reg_input[26]),
	.SDN(FE_OFN22_rst_int));
   DFCNQD1 \INS_SCR30b_reg_input_reg[29]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[29]),
	.Q(INS_SCR30b_reg_input[29]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[11]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[11]),
	.Q(INS_SCR30b_reg_input[11]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[3]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[26]),
	.Q(INS_SCR30b_S_reg[3]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[7]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[22]),
	.Q(INS_SCR30b_S_reg[7]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[5]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[24]),
	.Q(INS_SCR30b_S_reg[5]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[1]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[1]),
	.Q(INS_SCR30b_reg_input[1]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[5]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[5]),
	.Q(INS_SCR30b_reg_input[5]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[7]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[7]),
	.Q(INS_SCR30b_reg_input[7]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[3]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[3]),
	.Q(INS_SCR30b_reg_input[3]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[9]  (.CDN(FE_OFN23_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[9]),
	.Q(INS_SCR30b_reg_input[9]));
   DFCNQD1 \INS_SCR30b_S_reg_reg[1]  (.CDN(FE_OFN25_rst_int),
	.CP(CLKWordINT),
	.D(INS_SCR30b_DataOutSCR[28]),
	.Q(INS_SCR30b_S_reg[1]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[13]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[13]),
	.Q(INS_SCR30b_reg_input[13]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[15]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[15]),
	.Q(INS_SCR30b_reg_input[15]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[17]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[17]),
	.Q(INS_SCR30b_reg_input[17]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[19]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[19]),
	.Q(INS_SCR30b_reg_input[19]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[21]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[21]),
	.Q(INS_SCR30b_reg_input[21]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[23]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[23]),
	.Q(INS_SCR30b_reg_input[23]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[25]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[25]),
	.Q(INS_SCR30b_reg_input[25]));
   DFCNQD1 \INS_SCR30b_reg_input_reg[27]  (.CDN(FE_OFN22_rst_int),
	.CP(CLKWordINT),
	.D(DataIn[27]),
	.Q(INS_SCR30b_reg_input[27]));
   INVD1 g1390 (.I(REVCLK),
	.ZN(n_57));
   MUX2D0 g2 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[2]),
	.Z(n_178));
   CKMUX2D2 g2751 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[16]),
	.Z(n_179));
   MUX2D0 g2752 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[4]),
	.Z(n_180));
   CKMUX2D1 g2753 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[8]),
	.Z(n_181));
   MUX2D0 g2754 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[17]),
	.Z(n_182));
   MUX2D0 g2755 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[0]),
	.Z(n_183));
   MUX2D0 g2756 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[18]),
	.Z(n_184));
   MUX2D0 g2757 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[9]),
	.Z(n_185));
   MUX2D0 g2758 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[19]),
	.Z(n_186));
   CKMUX2D1 g2759 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[5]),
	.Z(n_187));
   MUX2D0 g2760 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[10]),
	.Z(n_188));
   MUX2D0 g2761 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[20]),
	.Z(n_189));
   MUX2D0 g2762 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[21]),
	.Z(n_190));
   MUX2D0 g2763 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[11]),
	.Z(n_191));
   MUX2D0 g2764 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[22]),
	.Z(n_192));
   MUX2D0 g2765 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[23]),
	.Z(n_193));
   MUX2D0 g2766 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[1]),
	.Z(n_194));
   CKMUX2D2 g2767 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[28]),
	.Z(n_195));
   MUX2D0 g2768 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[12]),
	.Z(n_196));
   MUX2D0 g2769 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[24]),
	.Z(n_197));
   MUX2D0 g2770 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[25]),
	.Z(n_198));
   MUX2D0 g2771 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[13]),
	.Z(n_199));
   MUX2D0 g2772 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[26]),
	.Z(n_200));
   MUX2D0 g2773 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[27]),
	.Z(n_201));
   MUX2D0 g2774 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[3]),
	.Z(n_202));
   MUX2D0 g2775 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[14]),
	.Z(n_203));
   CKMUX2D1 g2776 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[6]),
	.Z(n_204));
   MUX2D0 g2777 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[29]),
	.Z(n_205));
   MUX2D0 g2778 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[7]),
	.Z(n_206));
   MUX2D0 g2779 (.I0(REVData),
	.I1(n_78),
	.S(INS_SCR30b_reg_input[15]),
	.Z(n_207));
   DFSND1 \INS_PRBS7Gen32b_SA_reg[4]  (.CP(CLKWordINT),
	.D(n_1),
	.Q(DataPRBS7[27]),
	.QN(n_43),
	.SDN(FE_OFN26_rst_int));
   DFSND1 \INS_PRBS7Gen32b_SA_reg[3]  (.CP(CLKWordINT),
	.D(INS_PRBS7Gen32b_n_12),
	.Q(DataPRBS7[28]),
	.QN(n_40),
	.SDN(FE_OFN26_rst_int));
   AOI22D1 g2787 (.A1(n_194),
	.A2(FE_OFN10_n_48),
	.B1(FE_OFN8_n_41),
	.B2(FE_OFN7_DataPRBS7_29),
	.ZN(n_210));
   INR2D1 g2788 (.A1(n_40),
	.B1(n_168),
	.ZN(n_211));
   INR2D1 g2790 (.A1(n_37),
	.B1(FE_OFN6_DataPRBS7_30),
	.ZN(n_213));
   IAO22D1 g2792 (.A1(n_51),
	.A2(n_167),
	.B1(n_185),
	.B2(FE_OFN10_n_48),
	.ZN(n_215));
   AOI22D1 g2793 (.A1(n_191),
	.A2(FE_OFN10_n_48),
	.B1(FE_OFN8_n_41),
	.B2(DataPRBS7[23]),
	.ZN(n_216));
   IAO22D1 g2794 (.A1(FE_OFN7_DataPRBS7_29),
	.A2(n_167),
	.B1(n_207),
	.B2(FE_OFN10_n_48),
	.ZN(n_217));
   INR2D1 g2795 (.A1(n_38),
	.B1(n_166),
	.ZN(n_218));
   IAO22D1 g2796 (.A1(n_50),
	.A2(n_49),
	.B1(n_187),
	.B2(FE_OFN10_n_48),
	.ZN(n_219));
   INR2D1 g2797 (.A1(n_45),
	.B1(n_168),
	.ZN(n_220));
   IAO22D1 g2798 (.A1(n_47),
	.A2(n_49),
	.B1(n_206),
	.B2(FE_OFN10_n_48),
	.ZN(n_221));
   INR2D1 g2799 (.A1(FE_OFN9_n_43),
	.B1(n_168),
	.ZN(n_222));
   INR2D1 g2800 (.A1(n_38),
	.B1(n_168),
	.ZN(n_223));
   AOI22D1 g2802 (.A1(n_186),
	.A2(FE_OFN10_n_48),
	.B1(FE_OFN8_n_41),
	.B2(DataPRBS7[26]),
	.ZN(n_225));
   IAO22D1 g2803 (.A1(FE_OFN5_DataPRBS7_31),
	.A2(n_167),
	.B1(n_202),
	.B2(FE_OFN10_n_48),
	.ZN(n_226));
   IAO22D1 g2804 (.A1(FE_OFN9_n_43),
	.A2(n_49),
	.B1(n_199),
	.B2(FE_OFN10_n_48),
	.ZN(n_227));
   INR2D1 g2805 (.A1(n_42),
	.B1(INS_PRBS7Gen32b_n_12),
	.ZN(n_228));
   AO221D0 g2806 (.A1(INS_SCR30b_DataOutSCR[16]),
	.A2(FE_OFN11_n_58),
	.B1(DatatobeSent[30]),
	.B2(n_40),
	.C(n_116),
	.Z(n_229));
   AO221D0 g2807 (.A1(INS_SCR30b_DataOutSCR[18]),
	.A2(FE_OFN11_n_58),
	.B1(n_42),
	.B2(n_38),
	.C(n_139),
	.Z(n_230));
   AO221D0 g2808 (.A1(INS_SCR30b_DataOutSCR[4]),
	.A2(FE_OFN11_n_58),
	.B1(n_42),
	.B2(n_46),
	.C(n_147),
	.Z(n_231));
endmodule

